// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Duration.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BUILTIN_INTERFACES_MSG_DURATION_H_
#define _FAST_DDS_GENERATED_BUILTIN_INTERFACES_MSG_DURATION_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated Duration is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DURATION_SOURCE)
#define DURATION_DllAPI __declspec(dllexport)
#else
#define DURATION_DllAPI __declspec(dllimport)
#endif  // DURATION_SOURCE
#else
#define DURATION_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DURATION_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace builtin_interfaces {
namespace msg {

/*!
 * @brief This class represents the structure Duration defined by the user in the
 * IDL file.
 * @ingroup Duration
 */
class Duration : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object builtin_interfaces::msg::Duration that will be copied.
   */
  eProsima_user_DllExport Duration(const Duration& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object builtin_interfaces::msg::Duration that will be copied.
   */
  eProsima_user_DllExport Duration(Duration&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object builtin_interfaces::msg::Duration that will be copied.
   */
  eProsima_user_DllExport Duration& operator=(const Duration& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object builtin_interfaces::msg::Duration that will be copied.
   */
  eProsima_user_DllExport Duration& operator=(Duration&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x builtin_interfaces::msg::Duration object to compare.
   */
  eProsima_user_DllExport bool operator==(const Duration& x) const;

  /*!
   * @brief Comparison operator.
   * @param x builtin_interfaces::msg::Duration object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Duration& x) const;

  /*!
   * @brief This function sets a value in member sec
   * @param _sec New value for member sec
   */
  eProsima_user_DllExport void sec(int32 _sec);

  /*!
   * @brief This function returns the value of member sec
   * @return Value of member sec
   */
  eProsima_user_DllExport int32 sec() const;

  /*!
   * @brief This function returns a reference to member sec
   * @return Reference to member sec
   */
  eProsima_user_DllExport int32& sec();

  /*!
   * @brief This function sets a value in member nanosec
   * @param _nanosec New value for member nanosec
   */
  eProsima_user_DllExport void nanosec(uint32 _nanosec);

  /*!
   * @brief This function returns the value of member nanosec
   * @return Value of member nanosec
   */
  eProsima_user_DllExport uint32 nanosec() const;

  /*!
   * @brief This function returns a reference to member nanosec
   * @return Reference to member nanosec
   */
  eProsima_user_DllExport uint32& nanosec();

 private:
  int32 m_sec;
  uint32 m_nanosec;

 public:
  typedef Duration type;

  eProsima_user_DllExport Duration();

  eProsima_user_DllExport ~Duration() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return is_plain(eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    new (memory) Duration();
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;

};

}  // namespace msg
}  // namespace builtin_interfaces

#endif  // _FAST_DDS_GENERATED_BUILTIN_INTERFACES_MSG_DURATION_H_