[workspace]
channels = ["conda-forge", "robostack-humble"]
platforms = ["linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[dependencies]
booster_robotics_sdk = {path = "."}

[package]
name = "booster_robotics_sdk"
version = "1.4"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*" }

[package.build-dependencies]
cmake = "4.1.*"
patchelf = ">=0.17.2,<0.18"

[package.host-dependencies]
nanobind = "2.4.*"
python = "3.9.*"
numpy = ">=1.26,<3"
tinyxml2 = "==9"

[package.run-dependencies]
tinyxml2 = "==9"