// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ColorRGBA.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_STD_MSGS_MSG_COLORRGBA_H_
#define _FAST_DDS_GENERATED_STD_MSGS_MSG_COLORRGBA_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated ColorRGBA is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(COLORRGBA_SOURCE)
#define COLORRGBA_DllAPI __declspec(dllexport)
#else
#define COLORRGBA_DllAPI __declspec(dllimport)
#endif  // COLORRGBA_SOURCE
#else
#define COLORRGBA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define COLORRGBA_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace std_msgs {
namespace msg {

/*!
 * @brief This class represents the structure ColorRGBA defined by the user in the
 * IDL file.
 * @ingroup ColorRGBA
 */
class ColorRGBA : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object std_msgs::msg::ColorRGBA that will be copied.
   */
  eProsima_user_DllExport ColorRGBA(const ColorRGBA& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object std_msgs::msg::ColorRGBA that will be copied.
   */
  eProsima_user_DllExport ColorRGBA(ColorRGBA&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object std_msgs::msg::ColorRGBA that will be copied.
   */
  eProsima_user_DllExport ColorRGBA& operator=(const ColorRGBA& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object std_msgs::msg::ColorRGBA that will be copied.
   */
  eProsima_user_DllExport ColorRGBA& operator=(ColorRGBA&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x std_msgs::msg::ColorRGBA object to compare.
   */
  eProsima_user_DllExport bool operator==(const ColorRGBA& x) const;

  /*!
   * @brief Comparison operator.
   * @param x std_msgs::msg::ColorRGBA object to compare.
   */
  eProsima_user_DllExport bool operator!=(const ColorRGBA& x) const;

  /*!
   * @brief This function sets a value in member r
   * @param _r New value for member r
   */
  eProsima_user_DllExport void r(float _r);

  /*!
   * @brief This function returns the value of member r
   * @return Value of member r
   */
  eProsima_user_DllExport float r() const;

  /*!
   * @brief This function returns a reference to member r
   * @return Reference to member r
   */
  eProsima_user_DllExport float& r();

  /*!
   * @brief This function sets a value in member g
   * @param _g New value for member g
   */
  eProsima_user_DllExport void g(float _g);

  /*!
   * @brief This function returns the value of member g
   * @return Value of member g
   */
  eProsima_user_DllExport float g() const;

  /*!
   * @brief This function returns a reference to member g
   * @return Reference to member g
   */
  eProsima_user_DllExport float& g();

  /*!
   * @brief This function sets a value in member b
   * @param _b New value for member b
   */
  eProsima_user_DllExport void b(float _b);

  /*!
   * @brief This function returns the value of member b
   * @return Value of member b
   */
  eProsima_user_DllExport float b() const;

  /*!
   * @brief This function returns a reference to member b
   * @return Reference to member b
   */
  eProsima_user_DllExport float& b();

  /*!
   * @brief This function sets a value in member a
   * @param _a New value for member a
   */
  eProsima_user_DllExport void a(float _a);

  /*!
   * @brief This function returns the value of member a
   * @return Value of member a
   */
  eProsima_user_DllExport float a() const;

  /*!
   * @brief This function returns a reference to member a
   * @return Reference to member a
   */
  eProsima_user_DllExport float& a();

 private:
  float m_r;
  float m_g;
  float m_b;
  float m_a;

 public:
  typedef ColorRGBA type;

  eProsima_user_DllExport ColorRGBA();

  eProsima_user_DllExport ~ColorRGBA() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return is_plain(eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    new (memory) ColorRGBA();
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;

};

}  // namespace msg
}  // namespace std_msgs

#endif  // _FAST_DDS_GENERATED_STD_MSGS_MSG_COLORRGBA_H_