// Copyright (C) 2015-2023 Jonathan Müller and foonathan/memory contributors
// SPDX-License-Identifier: Zlib

#ifndef BOOSTER_FASTDDS_BOOSTER_FOONATHAN_MEMORY_DETAIL_CONTAINER_NODE_SIZES_HPP_INCLUDED
#define BOOSTER_FASTDDS_BOOSTER_FOONATHAN_MEMORY_DETAIL_CONTAINER_NODE_SIZES_HPP_INCLUDED

#include "container_node_sizes_impl.hpp"

#endif //BOOSTER_FASTDDS_BOOSTER_FOONATHAN_MEMORY_DETAIL_CONTAINER_NODE_SIZES_HPP_INCLUDED
