// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Hand.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_HAND_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_HAND_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <booster_fastdds/fastcdr/cdr/fixed_size_string.hpp>
#include <booster_fastdds/fastcdr/xcdr/external.hpp>
#include <booster_fastdds/fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <booster_fastdds/fastdds/rtps/common/InstanceHandle.h>
#include <booster_fastdds/fastdds/rtps/common/SerializedPayload.h>
#include <booster_fastdds/fastrtps/utils/md5.h>

#include <booster_fastdds/fastdds/dds/core/policy/QosPolicies.hpp>
#include <booster_fastdds/fastdds/dds/topic/TopicDataType.hpp>

#if !defined(BOOSTER_FASTDDS_GEN_API_VER) || (BOOSTER_FASTDDS_GEN_API_VER != 2)
#error \
    Generated Hand is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // BOOSTER_FASTDDS_GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(HAND_SOURCE)
#define HAND_DllAPI __declspec(dllexport)
#else
#define HAND_DllAPI __declspec(dllimport)
#endif  // HAND_SOURCE
#else
#define HAND_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define HAND_DllAPI
#endif  // _WIN32

namespace booster_eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace booster_eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the enumeration HandModel defined by the user in
 * the IDL file.
 * @ingroup Hand
 */
enum HandModel : uint32_t {
  HAND_MODEL_UNKNOWN,
  HAND_MODEL_INSPIRE_HAND_RH56DFX,
  HAND_MODEL_INSPIRE_GRIPPER_EG2_4X2,
  HAND_MODEL_INSPIRE_TOUCH_HAND_RH56DFTP
};
/*!
 * @brief This class represents the enumeration HandPos defined by the user in
 * the IDL file.
 * @ingroup Hand
 */
enum HandPos : uint32_t { HAND_POS_UNKNOWN, HAND_POS_LEFT, HAND_POS_RIGHT };

/*!
 * @brief This class represents the structure Hand defined by the user in the
 * IDL file.
 * @ingroup Hand
 */
class Hand : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Hand that will be
   * copied.
   */
  eProsima_user_DllExport Hand(const Hand& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Hand that will be
   * copied.
   */
  eProsima_user_DllExport Hand(Hand&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Hand that will be
   * copied.
   */
  eProsima_user_DllExport Hand& operator=(const Hand& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Hand that will be
   * copied.
   */
  eProsima_user_DllExport Hand& operator=(Hand&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Hand object to compare.
   */
  eProsima_user_DllExport bool operator==(const Hand& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Hand object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Hand& x) const;

  /*!
   * @brief This function sets a value in member model
   * @param _model New value for member model
   */
  eProsima_user_DllExport void model(booster_interface::msg::HandModel _model);

  /*!
   * @brief This function returns the value of member model
   * @return Value of member model
   */
  eProsima_user_DllExport booster_interface::msg::HandModel model() const;

  /*!
   * @brief This function returns a reference to member model
   * @return Reference to member model
   */
  eProsima_user_DllExport booster_interface::msg::HandModel& model();

  /*!
   * @brief This function sets a value in member pos
   * @param _pos New value for member pos
   */
  eProsima_user_DllExport void pos(booster_interface::msg::HandPos _pos);

  /*!
   * @brief This function returns the value of member pos
   * @return Value of member pos
   */
  eProsima_user_DllExport booster_interface::msg::HandPos pos() const;

  /*!
   * @brief This function returns a reference to member pos
   * @return Reference to member pos
   */
  eProsima_user_DllExport booster_interface::msg::HandPos& pos();

 private:
  booster_interface::msg::HandModel m_model{
      booster_interface::msg::HAND_MODEL_UNKNOWN};
  booster_interface::msg::HandPos m_pos{
      booster_interface::msg::HAND_POS_UNKNOWN};

 public:
 public:
  typedef Hand type;

  eProsima_user_DllExport Hand();

  eProsima_user_DllExport ~Hand() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};
class HandList : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::HandList that will
   * be copied.
   */
  eProsima_user_DllExport HandList(const HandList& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::HandList that will
   * be copied.
   */
  eProsima_user_DllExport HandList(HandList&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::HandList that will
   * be copied.
   */
  eProsima_user_DllExport HandList& operator=(const HandList& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::HandList that will
   * be copied.
   */
  eProsima_user_DllExport HandList& operator=(HandList&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::HandList object to compare.
   */
  eProsima_user_DllExport bool operator==(const HandList& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::HandList object to compare.
   */
  eProsima_user_DllExport bool operator!=(const HandList& x) const;

  /*!
   * @brief This function copies the value in member hands
   * @param _hands New value to be copied in member hands
   */
  eProsima_user_DllExport void hands(
      const std::vector<booster_interface::msg::Hand>& _hands);

  /*!
   * @brief This function moves the value in member hands
   * @param _hands New value to be moved in member hands
   */
  eProsima_user_DllExport void hands(
      std::vector<booster_interface::msg::Hand>&& _hands);

  /*!
   * @brief This function returns a constant reference to member hands
   * @return Constant reference to member hands
   */
  eProsima_user_DllExport const std::vector<booster_interface::msg::Hand>&
  hands() const;

  /*!
   * @brief This function returns a reference to member hands
   * @return Reference to member hands
   */
  eProsima_user_DllExport std::vector<booster_interface::msg::Hand>& hands();

 private:
  std::vector<booster_interface::msg::Hand> m_hands;

 public:
 public:
  typedef HandList type;

  eProsima_user_DllExport HandList();

  eProsima_user_DllExport ~HandList() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};
}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_HAND_H_
