// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ImuInfo.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_IMUINFO_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_IMUINFO_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <booster_fastdds/fastcdr/cdr/fixed_size_string.hpp>
#include <booster_fastdds/fastcdr/xcdr/external.hpp>
#include <booster_fastdds/fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <booster_fastdds/fastdds/rtps/common/InstanceHandle.h>
#include <booster_fastdds/fastdds/rtps/common/SerializedPayload.h>
#include <booster_fastdds/fastrtps/utils/md5.h>

#include <booster_fastdds/fastdds/dds/core/policy/QosPolicies.hpp>
#include <booster_fastdds/fastdds/dds/topic/TopicDataType.hpp>

#if !defined(BOOSTER_FASTDDS_GEN_API_VER) || (BOOSTER_FASTDDS_GEN_API_VER != 2)
#error \
    Generated ImuInfo is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // BOOSTER_FASTDDS_GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(IMUINFO_SOURCE)
#define IMUINFO_DllAPI __declspec(dllexport)
#else
#define IMUINFO_DllAPI __declspec(dllimport)
#endif  // IMUINFO_SOURCE
#else
#define IMUINFO_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define IMUINFO_DllAPI
#endif  // _WIN32

namespace booster_eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace booster_eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the enumeration ImuModel defined by the user in
 * the IDL file.
 * @ingroup ImuInfo
 */
enum ImuModel : uint32_t { IMU_MODEL_UNKNOWN, IMU_MODEL_HI13R4N };

/*!
 * @brief This class represents the structure ImuInfo defined by the user in the
 * IDL file.
 * @ingroup ImuInfo
 */
class ImuInfo : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::ImuInfo that will
   * be copied.
   */
  eProsima_user_DllExport ImuInfo(const ImuInfo& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::ImuInfo that will
   * be copied.
   */
  eProsima_user_DllExport ImuInfo(ImuInfo&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::ImuInfo that will
   * be copied.
   */
  eProsima_user_DllExport ImuInfo& operator=(const ImuInfo& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::ImuInfo that will
   * be copied.
   */
  eProsima_user_DllExport ImuInfo& operator=(ImuInfo&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::ImuInfo object to compare.
   */
  eProsima_user_DllExport bool operator==(const ImuInfo& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::ImuInfo object to compare.
   */
  eProsima_user_DllExport bool operator!=(const ImuInfo& x) const;

  /*!
   * @brief This function sets a value in member index
   * @param _index New value for member index
   */
  eProsima_user_DllExport void index(int32_t _index);

  /*!
   * @brief This function returns the value of member index
   * @return Value of member index
   */
  eProsima_user_DllExport int32_t index() const;

  /*!
   * @brief This function returns a reference to member index
   * @return Reference to member index
   */
  eProsima_user_DllExport int32_t& index();

  /*!
   * @brief This function copies the value in member name
   * @param _name New value to be copied in member name
   */
  eProsima_user_DllExport void name(const std::string& _name);

  /*!
   * @brief This function moves the value in member name
   * @param _name New value to be moved in member name
   */
  eProsima_user_DllExport void name(std::string&& _name);

  /*!
   * @brief This function returns a constant reference to member name
   * @return Constant reference to member name
   */
  eProsima_user_DllExport const std::string& name() const;

  /*!
   * @brief This function returns a reference to member name
   * @return Reference to member name
   */
  eProsima_user_DllExport std::string& name();

  /*!
   * @brief This function copies the value in member mount_position
   * @param _mount_position New value to be copied in member mount_position
   */
  eProsima_user_DllExport void mount_position(
      const std::string& _mount_position);

  /*!
   * @brief This function moves the value in member mount_position
   * @param _mount_position New value to be moved in member mount_position
   */
  eProsima_user_DllExport void mount_position(std::string&& _mount_position);

  /*!
   * @brief This function returns a constant reference to member mount_position
   * @return Constant reference to member mount_position
   */
  eProsima_user_DllExport const std::string& mount_position() const;

  /*!
   * @brief This function returns a reference to member mount_position
   * @return Reference to member mount_position
   */
  eProsima_user_DllExport std::string& mount_position();

  /*!
   * @brief This function sets a value in member model
   * @param _model New value for member model
   */
  eProsima_user_DllExport void model(booster_interface::msg::ImuModel _model);

  /*!
   * @brief This function returns the value of member model
   * @return Value of member model
   */
  eProsima_user_DllExport booster_interface::msg::ImuModel model() const;

  /*!
   * @brief This function returns a reference to member model
   * @return Reference to member model
   */
  eProsima_user_DllExport booster_interface::msg::ImuModel& model();

 private:
  int32_t m_index{0};
  std::string m_name;
  std::string m_mount_position;
  booster_interface::msg::ImuModel m_model{
      booster_interface::msg::IMU_MODEL_UNKNOWN};

 public:
 public:
  typedef ImuInfo type;

  eProsima_user_DllExport ImuInfo();

  eProsima_user_DllExport ~ImuInfo() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};
class ImuInfoList : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::ImuInfoList that
   * will be copied.
   */
  eProsima_user_DllExport ImuInfoList(const ImuInfoList& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::ImuInfoList that
   * will be copied.
   */
  eProsima_user_DllExport ImuInfoList(ImuInfoList&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::ImuInfoList that
   * will be copied.
   */
  eProsima_user_DllExport ImuInfoList& operator=(const ImuInfoList& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::ImuInfoList that
   * will be copied.
   */
  eProsima_user_DllExport ImuInfoList& operator=(ImuInfoList&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::ImuInfoList object to compare.
   */
  eProsima_user_DllExport bool operator==(const ImuInfoList& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::ImuInfoList object to compare.
   */
  eProsima_user_DllExport bool operator!=(const ImuInfoList& x) const;

  /*!
   * @brief This function copies the value in member imus
   * @param _imus New value to be copied in member imus
   */
  eProsima_user_DllExport void imus(
      const std::vector<booster_interface::msg::ImuInfo>& _imus);

  /*!
   * @brief This function moves the value in member imus
   * @param _imus New value to be moved in member imus
   */
  eProsima_user_DllExport void imus(
      std::vector<booster_interface::msg::ImuInfo>&& _imus);

  /*!
   * @brief This function returns a constant reference to member imus
   * @return Constant reference to member imus
   */
  eProsima_user_DllExport const std::vector<booster_interface::msg::ImuInfo>&
  imus() const;

  /*!
   * @brief This function returns a reference to member imus
   * @return Reference to member imus
   */
  eProsima_user_DllExport std::vector<booster_interface::msg::ImuInfo>& imus();

 private:
  std::vector<booster_interface::msg::ImuInfo> m_imus;

 public:
 public:
  typedef ImuInfoList type;

  eProsima_user_DllExport ImuInfoList();

  eProsima_user_DllExport ~ImuInfoList() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};
}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_IMUINFO_H_
