// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RobotModel.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_ROBOTMODEL_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_ROBOTMODEL_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <booster_fastdds/fastcdr/cdr/fixed_size_string.hpp>
#include <booster_fastdds/fastcdr/xcdr/external.hpp>
#include <booster_fastdds/fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <booster_fastdds/fastdds/rtps/common/InstanceHandle.h>
#include <booster_fastdds/fastdds/rtps/common/SerializedPayload.h>
#include <booster_fastdds/fastrtps/utils/md5.h>

#include <booster_fastdds/fastdds/dds/core/policy/QosPolicies.hpp>
#include <booster_fastdds/fastdds/dds/topic/TopicDataType.hpp>

#include "RobotModel.h"

#if !defined(BOOSTER_FASTDDS_GEN_API_VER) || (BOOSTER_FASTDDS_GEN_API_VER != 2)
#error \
    Generated RobotModel is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // BOOSTER_FASTDDS_GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#include "../../idl/geometry_msgs/Point.h"
#include "../../idl/geometry_msgs/Vector3.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ROBOTMODEL_SOURCE)
#define ROBOTMODEL_DllAPI __declspec(dllexport)
#else
#define ROBOTMODEL_DllAPI __declspec(dllimport)
#endif  // ROBOTMODEL_SOURCE
#else
#define ROBOTMODEL_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ROBOTMODEL_DllAPI
#endif  // _WIN32

namespace booster_eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace booster_eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the structure Origin defined by the user in the
 * IDL file.
 * @ingroup RobotModel
 */
class Origin : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Origin that will
   * be copied.
   */
  eProsima_user_DllExport Origin(const Origin& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Origin that will
   * be copied.
   */
  eProsima_user_DllExport Origin(Origin&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Origin that will
   * be copied.
   */
  eProsima_user_DllExport Origin& operator=(const Origin& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Origin that will
   * be copied.
   */
  eProsima_user_DllExport Origin& operator=(Origin&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Origin object to compare.
   */
  eProsima_user_DllExport bool operator==(const Origin& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Origin object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Origin& x) const;

  /*!
   * @brief This function copies the value in member xyz
   * @param _xyz New value to be copied in member xyz
   */
  eProsima_user_DllExport void xyz(const geometry_msgs::msg::Point& _xyz);

  /*!
   * @brief This function moves the value in member xyz
   * @param _xyz New value to be moved in member xyz
   */
  eProsima_user_DllExport void xyz(geometry_msgs::msg::Point&& _xyz);

  /*!
   * @brief This function returns a constant reference to member xyz
   * @return Constant reference to member xyz
   */
  eProsima_user_DllExport const geometry_msgs::msg::Point& xyz() const;

  /*!
   * @brief This function returns a reference to member xyz
   * @return Reference to member xyz
   */
  eProsima_user_DllExport geometry_msgs::msg::Point& xyz();

  /*!
   * @brief This function copies the value in member rpy
   * @param _rpy New value to be copied in member rpy
   */
  eProsima_user_DllExport void rpy(const geometry_msgs::msg::Vector3& _rpy);

  /*!
   * @brief This function moves the value in member rpy
   * @param _rpy New value to be moved in member rpy
   */
  eProsima_user_DllExport void rpy(geometry_msgs::msg::Vector3&& _rpy);

  /*!
   * @brief This function returns a constant reference to member rpy
   * @return Constant reference to member rpy
   */
  eProsima_user_DllExport const geometry_msgs::msg::Vector3& rpy() const;

  /*!
   * @brief This function returns a reference to member rpy
   * @return Reference to member rpy
   */
  eProsima_user_DllExport geometry_msgs::msg::Vector3& rpy();

 private:
  geometry_msgs::msg::Point m_xyz;
  geometry_msgs::msg::Vector3 m_rpy;

 public:
 public:
  typedef Origin DdsTopicMessageType;

  eProsima_user_DllExport Origin();

  eProsima_user_DllExport ~Origin() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure Inertia defined by the user in the
 * IDL file.
 * @ingroup RobotModel
 */
class Inertia : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Inertia that will
   * be copied.
   */
  eProsima_user_DllExport Inertia(const Inertia& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Inertia that will
   * be copied.
   */
  eProsima_user_DllExport Inertia(Inertia&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Inertia that will
   * be copied.
   */
  eProsima_user_DllExport Inertia& operator=(const Inertia& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Inertia that will
   * be copied.
   */
  eProsima_user_DllExport Inertia& operator=(Inertia&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Inertia object to compare.
   */
  eProsima_user_DllExport bool operator==(const Inertia& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Inertia object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Inertia& x) const;

  /*!
   * @brief This function sets a value in member ixx
   * @param _ixx New value for member ixx
   */
  eProsima_user_DllExport void ixx(double _ixx);

  /*!
   * @brief This function returns the value of member ixx
   * @return Value of member ixx
   */
  eProsima_user_DllExport double ixx() const;

  /*!
   * @brief This function returns a reference to member ixx
   * @return Reference to member ixx
   */
  eProsima_user_DllExport double& ixx();

  /*!
   * @brief This function sets a value in member ixy
   * @param _ixy New value for member ixy
   */
  eProsima_user_DllExport void ixy(double _ixy);

  /*!
   * @brief This function returns the value of member ixy
   * @return Value of member ixy
   */
  eProsima_user_DllExport double ixy() const;

  /*!
   * @brief This function returns a reference to member ixy
   * @return Reference to member ixy
   */
  eProsima_user_DllExport double& ixy();

  /*!
   * @brief This function sets a value in member ixz
   * @param _ixz New value for member ixz
   */
  eProsima_user_DllExport void ixz(double _ixz);

  /*!
   * @brief This function returns the value of member ixz
   * @return Value of member ixz
   */
  eProsima_user_DllExport double ixz() const;

  /*!
   * @brief This function returns a reference to member ixz
   * @return Reference to member ixz
   */
  eProsima_user_DllExport double& ixz();

  /*!
   * @brief This function sets a value in member iyy
   * @param _iyy New value for member iyy
   */
  eProsima_user_DllExport void iyy(double _iyy);

  /*!
   * @brief This function returns the value of member iyy
   * @return Value of member iyy
   */
  eProsima_user_DllExport double iyy() const;

  /*!
   * @brief This function returns a reference to member iyy
   * @return Reference to member iyy
   */
  eProsima_user_DllExport double& iyy();

  /*!
   * @brief This function sets a value in member iyz
   * @param _iyz New value for member iyz
   */
  eProsima_user_DllExport void iyz(double _iyz);

  /*!
   * @brief This function returns the value of member iyz
   * @return Value of member iyz
   */
  eProsima_user_DllExport double iyz() const;

  /*!
   * @brief This function returns a reference to member iyz
   * @return Reference to member iyz
   */
  eProsima_user_DllExport double& iyz();

  /*!
   * @brief This function sets a value in member izz
   * @param _izz New value for member izz
   */
  eProsima_user_DllExport void izz(double _izz);

  /*!
   * @brief This function returns the value of member izz
   * @return Value of member izz
   */
  eProsima_user_DllExport double izz() const;

  /*!
   * @brief This function returns a reference to member izz
   * @return Reference to member izz
   */
  eProsima_user_DllExport double& izz();

 private:
  double m_ixx{0.0};
  double m_ixy{0.0};
  double m_ixz{0.0};
  double m_iyy{0.0};
  double m_iyz{0.0};
  double m_izz{0.0};

 public:
 public:
  typedef Inertia DdsTopicMessageType;

  eProsima_user_DllExport Inertia();

  eProsima_user_DllExport ~Inertia() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure Inertial defined by the user in
 * the IDL file.
 * @ingroup RobotModel
 */
class Inertial : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Inertial that will
   * be copied.
   */
  eProsima_user_DllExport Inertial(const Inertial& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Inertial that will
   * be copied.
   */
  eProsima_user_DllExport Inertial(Inertial&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Inertial that will
   * be copied.
   */
  eProsima_user_DllExport Inertial& operator=(const Inertial& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Inertial that will
   * be copied.
   */
  eProsima_user_DllExport Inertial& operator=(Inertial&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Inertial object to compare.
   */
  eProsima_user_DllExport bool operator==(const Inertial& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Inertial object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Inertial& x) const;

  /*!
   * @brief This function copies the value in member origin
   * @param _origin New value to be copied in member origin
   */
  eProsima_user_DllExport void origin(
      const booster_interface::msg::Origin& _origin);

  /*!
   * @brief This function moves the value in member origin
   * @param _origin New value to be moved in member origin
   */
  eProsima_user_DllExport void origin(booster_interface::msg::Origin&& _origin);

  /*!
   * @brief This function returns a constant reference to member origin
   * @return Constant reference to member origin
   */
  eProsima_user_DllExport const booster_interface::msg::Origin& origin() const;

  /*!
   * @brief This function returns a reference to member origin
   * @return Reference to member origin
   */
  eProsima_user_DllExport booster_interface::msg::Origin& origin();

  /*!
   * @brief This function sets a value in member mass
   * @param _mass New value for member mass
   */
  eProsima_user_DllExport void mass(double _mass);

  /*!
   * @brief This function returns the value of member mass
   * @return Value of member mass
   */
  eProsima_user_DllExport double mass() const;

  /*!
   * @brief This function returns a reference to member mass
   * @return Reference to member mass
   */
  eProsima_user_DllExport double& mass();

  /*!
   * @brief This function copies the value in member inertia
   * @param _inertia New value to be copied in member inertia
   */
  eProsima_user_DllExport void inertia(
      const booster_interface::msg::Inertia& _inertia);

  /*!
   * @brief This function moves the value in member inertia
   * @param _inertia New value to be moved in member inertia
   */
  eProsima_user_DllExport void inertia(
      booster_interface::msg::Inertia&& _inertia);

  /*!
   * @brief This function returns a constant reference to member inertia
   * @return Constant reference to member inertia
   */
  eProsima_user_DllExport const booster_interface::msg::Inertia& inertia()
      const;

  /*!
   * @brief This function returns a reference to member inertia
   * @return Reference to member inertia
   */
  eProsima_user_DllExport booster_interface::msg::Inertia& inertia();

 private:
  booster_interface::msg::Origin m_origin;
  double m_mass{0.0};
  booster_interface::msg::Inertia m_inertia;

 public:
 public:
  typedef Inertial DdsTopicMessageType;

  eProsima_user_DllExport Inertial();

  eProsima_user_DllExport ~Inertial() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure Box defined by the user in the IDL
 * file.
 * @ingroup RobotModel
 */
class Box : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Box that will be
   * copied.
   */
  eProsima_user_DllExport Box(const Box& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Box that will be
   * copied.
   */
  eProsima_user_DllExport Box(Box&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Box that will be
   * copied.
   */
  eProsima_user_DllExport Box& operator=(const Box& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Box that will be
   * copied.
   */
  eProsima_user_DllExport Box& operator=(Box&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Box object to compare.
   */
  eProsima_user_DllExport bool operator==(const Box& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Box object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Box& x) const;

  /*!
   * @brief This function copies the value in member size
   * @param _size New value to be copied in member size
   */
  eProsima_user_DllExport void size(const geometry_msgs::msg::Vector3& _size);

  /*!
   * @brief This function moves the value in member size
   * @param _size New value to be moved in member size
   */
  eProsima_user_DllExport void size(geometry_msgs::msg::Vector3&& _size);

  /*!
   * @brief This function returns a constant reference to member size
   * @return Constant reference to member size
   */
  eProsima_user_DllExport const geometry_msgs::msg::Vector3& size() const;

  /*!
   * @brief This function returns a reference to member size
   * @return Reference to member size
   */
  eProsima_user_DllExport geometry_msgs::msg::Vector3& size();

 private:
  geometry_msgs::msg::Vector3 m_size;

 public:
 public:
  typedef Box DdsTopicMessageType;

  eProsima_user_DllExport Box();

  eProsima_user_DllExport ~Box() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure Cylinder defined by the user in
 * the IDL file.
 * @ingroup RobotModel
 */
class Cylinder : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Cylinder that will
   * be copied.
   */
  eProsima_user_DllExport Cylinder(const Cylinder& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Cylinder that will
   * be copied.
   */
  eProsima_user_DllExport Cylinder(Cylinder&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Cylinder that will
   * be copied.
   */
  eProsima_user_DllExport Cylinder& operator=(const Cylinder& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Cylinder that will
   * be copied.
   */
  eProsima_user_DllExport Cylinder& operator=(Cylinder&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Cylinder object to compare.
   */
  eProsima_user_DllExport bool operator==(const Cylinder& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Cylinder object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Cylinder& x) const;

  /*!
   * @brief This function sets a value in member radius
   * @param _radius New value for member radius
   */
  eProsima_user_DllExport void radius(double _radius);

  /*!
   * @brief This function returns the value of member radius
   * @return Value of member radius
   */
  eProsima_user_DllExport double radius() const;

  /*!
   * @brief This function returns a reference to member radius
   * @return Reference to member radius
   */
  eProsima_user_DllExport double& radius();

  /*!
   * @brief This function sets a value in member length
   * @param _length New value for member length
   */
  eProsima_user_DllExport void length(double _length);

  /*!
   * @brief This function returns the value of member length
   * @return Value of member length
   */
  eProsima_user_DllExport double length() const;

  /*!
   * @brief This function returns a reference to member length
   * @return Reference to member length
   */
  eProsima_user_DllExport double& length();

 private:
  double m_radius{0.0};
  double m_length{0.0};

 public:
 public:
  typedef Cylinder DdsTopicMessageType;

  eProsima_user_DllExport Cylinder();

  eProsima_user_DllExport ~Cylinder() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure Sphere defined by the user in the
 * IDL file.
 * @ingroup RobotModel
 */
class Sphere : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Sphere that will
   * be copied.
   */
  eProsima_user_DllExport Sphere(const Sphere& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Sphere that will
   * be copied.
   */
  eProsima_user_DllExport Sphere(Sphere&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Sphere that will
   * be copied.
   */
  eProsima_user_DllExport Sphere& operator=(const Sphere& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Sphere that will
   * be copied.
   */
  eProsima_user_DllExport Sphere& operator=(Sphere&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Sphere object to compare.
   */
  eProsima_user_DllExport bool operator==(const Sphere& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Sphere object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Sphere& x) const;

  /*!
   * @brief This function sets a value in member radius
   * @param _radius New value for member radius
   */
  eProsima_user_DllExport void radius(double _radius);

  /*!
   * @brief This function returns the value of member radius
   * @return Value of member radius
   */
  eProsima_user_DllExport double radius() const;

  /*!
   * @brief This function returns a reference to member radius
   * @return Reference to member radius
   */
  eProsima_user_DllExport double& radius();

 private:
  double m_radius{0.0};

 public:
 public:
  typedef Sphere DdsTopicMessageType;

  eProsima_user_DllExport Sphere();

  eProsima_user_DllExport ~Sphere() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure Mesh defined by the user in the
 * IDL file.
 * @ingroup RobotModel
 */
class Mesh : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Mesh that will be
   * copied.
   */
  eProsima_user_DllExport Mesh(const Mesh& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Mesh that will be
   * copied.
   */
  eProsima_user_DllExport Mesh(Mesh&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Mesh that will be
   * copied.
   */
  eProsima_user_DllExport Mesh& operator=(const Mesh& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Mesh that will be
   * copied.
   */
  eProsima_user_DllExport Mesh& operator=(Mesh&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Mesh object to compare.
   */
  eProsima_user_DllExport bool operator==(const Mesh& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Mesh object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Mesh& x) const;

  /*!
   * @brief This function copies the value in member filename
   * @param _filename New value to be copied in member filename
   */
  eProsima_user_DllExport void filename(const std::string& _filename);

  /*!
   * @brief This function moves the value in member filename
   * @param _filename New value to be moved in member filename
   */
  eProsima_user_DllExport void filename(std::string&& _filename);

  /*!
   * @brief This function returns a constant reference to member filename
   * @return Constant reference to member filename
   */
  eProsima_user_DllExport const std::string& filename() const;

  /*!
   * @brief This function returns a reference to member filename
   * @return Reference to member filename
   */
  eProsima_user_DllExport std::string& filename();

  /*!
   * @brief This function copies the value in member scale
   * @param _scale New value to be copied in member scale
   */
  eProsima_user_DllExport void scale(const geometry_msgs::msg::Vector3& _scale);

  /*!
   * @brief This function moves the value in member scale
   * @param _scale New value to be moved in member scale
   */
  eProsima_user_DllExport void scale(geometry_msgs::msg::Vector3&& _scale);

  /*!
   * @brief This function returns a constant reference to member scale
   * @return Constant reference to member scale
   */
  eProsima_user_DllExport const geometry_msgs::msg::Vector3& scale() const;

  /*!
   * @brief This function returns a reference to member scale
   * @return Reference to member scale
   */
  eProsima_user_DllExport geometry_msgs::msg::Vector3& scale();

 private:
  std::string m_filename;
  geometry_msgs::msg::Vector3 m_scale;

 public:
 public:
  typedef Mesh DdsTopicMessageType;

  eProsima_user_DllExport Mesh();

  eProsima_user_DllExport ~Mesh() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};
/*!
 * @brief This class represents the enumeration GeometryType defined by the user
 * in the IDL file.
 * @ingroup RobotModel
 */
enum GeometryType : uint32_t {
  GEOMETRY_TYPE_BOX,
  GEOMETRY_TYPE_CYLINDER,
  GEOMETRY_TYPE_SPHERE,
  GEOMETRY_TYPE_MESH
};

/*!
 * @brief This class represents the structure Geometry defined by the user in
 * the IDL file.
 * @ingroup RobotModel
 */
class Geometry : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Geometry that will
   * be copied.
   */
  eProsima_user_DllExport Geometry(const Geometry& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Geometry that will
   * be copied.
   */
  eProsima_user_DllExport Geometry(Geometry&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Geometry that will
   * be copied.
   */
  eProsima_user_DllExport Geometry& operator=(const Geometry& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Geometry that will
   * be copied.
   */
  eProsima_user_DllExport Geometry& operator=(Geometry&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Geometry object to compare.
   */
  eProsima_user_DllExport bool operator==(const Geometry& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Geometry object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Geometry& x) const;

  /*!
   * @brief This function sets a value in member type
   * @param _type New value for member type
   */
  eProsima_user_DllExport void type(booster_interface::msg::GeometryType _type);

  /*!
   * @brief This function returns the value of member type
   * @return Value of member type
   */
  eProsima_user_DllExport booster_interface::msg::GeometryType type() const;

  /*!
   * @brief This function returns a reference to member type
   * @return Reference to member type
   */
  eProsima_user_DllExport booster_interface::msg::GeometryType& type();

  /*!
   * @brief This function copies the value in member box
   * @param _box New value to be copied in member box
   */
  eProsima_user_DllExport void box(const booster_interface::msg::Box& _box);

  /*!
   * @brief This function moves the value in member box
   * @param _box New value to be moved in member box
   */
  eProsima_user_DllExport void box(booster_interface::msg::Box&& _box);

  /*!
   * @brief This function returns a constant reference to member box
   * @return Constant reference to member box
   */
  eProsima_user_DllExport const booster_interface::msg::Box& box() const;

  /*!
   * @brief This function returns a reference to member box
   * @return Reference to member box
   */
  eProsima_user_DllExport booster_interface::msg::Box& box();

  /*!
   * @brief This function copies the value in member cylinder
   * @param _cylinder New value to be copied in member cylinder
   */
  eProsima_user_DllExport void cylinder(
      const booster_interface::msg::Cylinder& _cylinder);

  /*!
   * @brief This function moves the value in member cylinder
   * @param _cylinder New value to be moved in member cylinder
   */
  eProsima_user_DllExport void cylinder(
      booster_interface::msg::Cylinder&& _cylinder);

  /*!
   * @brief This function returns a constant reference to member cylinder
   * @return Constant reference to member cylinder
   */
  eProsima_user_DllExport const booster_interface::msg::Cylinder& cylinder()
      const;

  /*!
   * @brief This function returns a reference to member cylinder
   * @return Reference to member cylinder
   */
  eProsima_user_DllExport booster_interface::msg::Cylinder& cylinder();

  /*!
   * @brief This function copies the value in member sphere
   * @param _sphere New value to be copied in member sphere
   */
  eProsima_user_DllExport void sphere(
      const booster_interface::msg::Sphere& _sphere);

  /*!
   * @brief This function moves the value in member sphere
   * @param _sphere New value to be moved in member sphere
   */
  eProsima_user_DllExport void sphere(booster_interface::msg::Sphere&& _sphere);

  /*!
   * @brief This function returns a constant reference to member sphere
   * @return Constant reference to member sphere
   */
  eProsima_user_DllExport const booster_interface::msg::Sphere& sphere() const;

  /*!
   * @brief This function returns a reference to member sphere
   * @return Reference to member sphere
   */
  eProsima_user_DllExport booster_interface::msg::Sphere& sphere();

  /*!
   * @brief This function copies the value in member mesh
   * @param _mesh New value to be copied in member mesh
   */
  eProsima_user_DllExport void mesh(const booster_interface::msg::Mesh& _mesh);

  /*!
   * @brief This function moves the value in member mesh
   * @param _mesh New value to be moved in member mesh
   */
  eProsima_user_DllExport void mesh(booster_interface::msg::Mesh&& _mesh);

  /*!
   * @brief This function returns a constant reference to member mesh
   * @return Constant reference to member mesh
   */
  eProsima_user_DllExport const booster_interface::msg::Mesh& mesh() const;

  /*!
   * @brief This function returns a reference to member mesh
   * @return Reference to member mesh
   */
  eProsima_user_DllExport booster_interface::msg::Mesh& mesh();

 private:
  booster_interface::msg::GeometryType m_type{
      booster_interface::msg::GEOMETRY_TYPE_BOX};
  booster_interface::msg::Box m_box;
  booster_interface::msg::Cylinder m_cylinder;
  booster_interface::msg::Sphere m_sphere;
  booster_interface::msg::Mesh m_mesh;

 public:
 public:
  typedef Geometry DdsTopicMessageType;

  eProsima_user_DllExport Geometry();

  eProsima_user_DllExport ~Geometry() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure Collision defined by the user in
 * the IDL file.
 * @ingroup RobotModel
 */
class Collision : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Collision that
   * will be copied.
   */
  eProsima_user_DllExport Collision(const Collision& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Collision that
   * will be copied.
   */
  eProsima_user_DllExport Collision(Collision&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Collision that
   * will be copied.
   */
  eProsima_user_DllExport Collision& operator=(const Collision& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Collision that
   * will be copied.
   */
  eProsima_user_DllExport Collision& operator=(Collision&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Collision object to compare.
   */
  eProsima_user_DllExport bool operator==(const Collision& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Collision object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Collision& x) const;

  /*!
   * @brief This function copies the value in member origin
   * @param _origin New value to be copied in member origin
   */
  eProsima_user_DllExport void origin(
      const booster_interface::msg::Origin& _origin);

  /*!
   * @brief This function moves the value in member origin
   * @param _origin New value to be moved in member origin
   */
  eProsima_user_DllExport void origin(booster_interface::msg::Origin&& _origin);

  /*!
   * @brief This function returns a constant reference to member origin
   * @return Constant reference to member origin
   */
  eProsima_user_DllExport const booster_interface::msg::Origin& origin() const;

  /*!
   * @brief This function returns a reference to member origin
   * @return Reference to member origin
   */
  eProsima_user_DllExport booster_interface::msg::Origin& origin();

  /*!
   * @brief This function copies the value in member geometry
   * @param _geometry New value to be copied in member geometry
   */
  eProsima_user_DllExport void geometry(
      const booster_interface::msg::Geometry& _geometry);

  /*!
   * @brief This function moves the value in member geometry
   * @param _geometry New value to be moved in member geometry
   */
  eProsima_user_DllExport void geometry(
      booster_interface::msg::Geometry&& _geometry);

  /*!
   * @brief This function returns a constant reference to member geometry
   * @return Constant reference to member geometry
   */
  eProsima_user_DllExport const booster_interface::msg::Geometry& geometry()
      const;

  /*!
   * @brief This function returns a reference to member geometry
   * @return Reference to member geometry
   */
  eProsima_user_DllExport booster_interface::msg::Geometry& geometry();

 private:
  booster_interface::msg::Origin m_origin;
  booster_interface::msg::Geometry m_geometry;

 public:
 public:
  typedef Collision DdsTopicMessageType;

  eProsima_user_DllExport Collision();

  eProsima_user_DllExport ~Collision() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure Link defined by the user in the
 * IDL file.
 * @ingroup RobotModel
 */
class Link : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Link that will be
   * copied.
   */
  eProsima_user_DllExport Link(const Link& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Link that will be
   * copied.
   */
  eProsima_user_DllExport Link(Link&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Link that will be
   * copied.
   */
  eProsima_user_DllExport Link& operator=(const Link& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Link that will be
   * copied.
   */
  eProsima_user_DllExport Link& operator=(Link&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Link object to compare.
   */
  eProsima_user_DllExport bool operator==(const Link& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Link object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Link& x) const;

  /*!
   * @brief This function copies the value in member name
   * @param _name New value to be copied in member name
   */
  eProsima_user_DllExport void name(const std::string& _name);

  /*!
   * @brief This function moves the value in member name
   * @param _name New value to be moved in member name
   */
  eProsima_user_DllExport void name(std::string&& _name);

  /*!
   * @brief This function returns a constant reference to member name
   * @return Constant reference to member name
   */
  eProsima_user_DllExport const std::string& name() const;

  /*!
   * @brief This function returns a reference to member name
   * @return Reference to member name
   */
  eProsima_user_DllExport std::string& name();

  /*!
   * @brief This function copies the value in member inertial
   * @param _inertial New value to be copied in member inertial
   */
  eProsima_user_DllExport void inertial(
      const booster_interface::msg::Inertial& _inertial);

  /*!
   * @brief This function moves the value in member inertial
   * @param _inertial New value to be moved in member inertial
   */
  eProsima_user_DllExport void inertial(
      booster_interface::msg::Inertial&& _inertial);

  /*!
   * @brief This function returns a constant reference to member inertial
   * @return Constant reference to member inertial
   */
  eProsima_user_DllExport const booster_interface::msg::Inertial& inertial()
      const;

  /*!
   * @brief This function returns a reference to member inertial
   * @return Reference to member inertial
   */
  eProsima_user_DllExport booster_interface::msg::Inertial& inertial();

  /*!
   * @brief This function copies the value in member collisions
   * @param _collisions New value to be copied in member collisions
   */
  eProsima_user_DllExport void collisions(
      const std::vector<booster_interface::msg::Collision>& _collisions);

  /*!
   * @brief This function moves the value in member collisions
   * @param _collisions New value to be moved in member collisions
   */
  eProsima_user_DllExport void collisions(
      std::vector<booster_interface::msg::Collision>&& _collisions);

  /*!
   * @brief This function returns a constant reference to member collisions
   * @return Constant reference to member collisions
   */
  eProsima_user_DllExport const std::vector<booster_interface::msg::Collision>&
  collisions() const;

  /*!
   * @brief This function returns a reference to member collisions
   * @return Reference to member collisions
   */
  eProsima_user_DllExport std::vector<booster_interface::msg::Collision>&
  collisions();

 private:
  std::string m_name;
  booster_interface::msg::Inertial m_inertial;
  std::vector<booster_interface::msg::Collision> m_collisions;

 public:
 public:
  typedef Link DdsTopicMessageType;

  eProsima_user_DllExport Link();

  eProsima_user_DllExport ~Link() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};
/*!
 * @brief This class represents the enumeration JointType defined by the user in
 * the IDL file.
 * @ingroup RobotModel
 */
enum JointType : uint32_t {
  JOINT_TYPE_FIXED,
  JOINT_TYPE_REVOLUTE,
  JOINT_TYPE_CONTINUOUS,
  JOINT_TYPE_PRISMATIC,
  JOINT_TYPE_PLANAR,
  JOINT_TYPE_FLOATING
};

/*!
 * @brief This class represents the structure JointLimit defined by the user in
 * the IDL file.
 * @ingroup RobotModel
 */
class JointLimit : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::JointLimit that
   * will be copied.
   */
  eProsima_user_DllExport JointLimit(const JointLimit& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::JointLimit that
   * will be copied.
   */
  eProsima_user_DllExport JointLimit(JointLimit&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::JointLimit that
   * will be copied.
   */
  eProsima_user_DllExport JointLimit& operator=(const JointLimit& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::JointLimit that
   * will be copied.
   */
  eProsima_user_DllExport JointLimit& operator=(JointLimit&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::JointLimit object to compare.
   */
  eProsima_user_DllExport bool operator==(const JointLimit& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::JointLimit object to compare.
   */
  eProsima_user_DllExport bool operator!=(const JointLimit& x) const;

  /*!
   * @brief This function sets a value in member lower
   * @param _lower New value for member lower
   */
  eProsima_user_DllExport void lower(double _lower);

  /*!
   * @brief This function returns the value of member lower
   * @return Value of member lower
   */
  eProsima_user_DllExport double lower() const;

  /*!
   * @brief This function returns a reference to member lower
   * @return Reference to member lower
   */
  eProsima_user_DllExport double& lower();

  /*!
   * @brief This function sets a value in member upper
   * @param _upper New value for member upper
   */
  eProsima_user_DllExport void upper(double _upper);

  /*!
   * @brief This function returns the value of member upper
   * @return Value of member upper
   */
  eProsima_user_DllExport double upper() const;

  /*!
   * @brief This function returns a reference to member upper
   * @return Reference to member upper
   */
  eProsima_user_DllExport double& upper();

  /*!
   * @brief This function sets a value in member effort
   * @param _effort New value for member effort
   */
  eProsima_user_DllExport void effort(double _effort);

  /*!
   * @brief This function returns the value of member effort
   * @return Value of member effort
   */
  eProsima_user_DllExport double effort() const;

  /*!
   * @brief This function returns a reference to member effort
   * @return Reference to member effort
   */
  eProsima_user_DllExport double& effort();

  /*!
   * @brief This function sets a value in member velocity
   * @param _velocity New value for member velocity
   */
  eProsima_user_DllExport void velocity(double _velocity);

  /*!
   * @brief This function returns the value of member velocity
   * @return Value of member velocity
   */
  eProsima_user_DllExport double velocity() const;

  /*!
   * @brief This function returns a reference to member velocity
   * @return Reference to member velocity
   */
  eProsima_user_DllExport double& velocity();

 private:
  double m_lower{0.0};
  double m_upper{0.0};
  double m_effort{0.0};
  double m_velocity{0.0};

 public:
 public:
  typedef JointLimit DdsTopicMessageType;

  eProsima_user_DllExport JointLimit();

  eProsima_user_DllExport ~JointLimit() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure Joint defined by the user in the
 * IDL file.
 * @ingroup RobotModel
 */
class Joint : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Joint that will be
   * copied.
   */
  eProsima_user_DllExport Joint(const Joint& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Joint that will be
   * copied.
   */
  eProsima_user_DllExport Joint(Joint&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Joint that will be
   * copied.
   */
  eProsima_user_DllExport Joint& operator=(const Joint& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Joint that will be
   * copied.
   */
  eProsima_user_DllExport Joint& operator=(Joint&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Joint object to compare.
   */
  eProsima_user_DllExport bool operator==(const Joint& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Joint object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Joint& x) const;

  /*!
   * @brief This function copies the value in member name
   * @param _name New value to be copied in member name
   */
  eProsima_user_DllExport void name(const std::string& _name);

  /*!
   * @brief This function moves the value in member name
   * @param _name New value to be moved in member name
   */
  eProsima_user_DllExport void name(std::string&& _name);

  /*!
   * @brief This function returns a constant reference to member name
   * @return Constant reference to member name
   */
  eProsima_user_DllExport const std::string& name() const;

  /*!
   * @brief This function returns a reference to member name
   * @return Reference to member name
   */
  eProsima_user_DllExport std::string& name();

  /*!
   * @brief This function sets a value in member type
   * @param _type New value for member type
   */
  eProsima_user_DllExport void type(booster_interface::msg::JointType _type);

  /*!
   * @brief This function returns the value of member type
   * @return Value of member type
   */
  eProsima_user_DllExport booster_interface::msg::JointType type() const;

  /*!
   * @brief This function returns a reference to member type
   * @return Reference to member type
   */
  eProsima_user_DllExport booster_interface::msg::JointType& type();

  /*!
   * @brief This function copies the value in member parent_link
   * @param _parent_link New value to be copied in member parent_link
   */
  eProsima_user_DllExport void parent_link(const std::string& _parent_link);

  /*!
   * @brief This function moves the value in member parent_link
   * @param _parent_link New value to be moved in member parent_link
   */
  eProsima_user_DllExport void parent_link(std::string&& _parent_link);

  /*!
   * @brief This function returns a constant reference to member parent_link
   * @return Constant reference to member parent_link
   */
  eProsima_user_DllExport const std::string& parent_link() const;

  /*!
   * @brief This function returns a reference to member parent_link
   * @return Reference to member parent_link
   */
  eProsima_user_DllExport std::string& parent_link();

  /*!
   * @brief This function copies the value in member child_link
   * @param _child_link New value to be copied in member child_link
   */
  eProsima_user_DllExport void child_link(const std::string& _child_link);

  /*!
   * @brief This function moves the value in member child_link
   * @param _child_link New value to be moved in member child_link
   */
  eProsima_user_DllExport void child_link(std::string&& _child_link);

  /*!
   * @brief This function returns a constant reference to member child_link
   * @return Constant reference to member child_link
   */
  eProsima_user_DllExport const std::string& child_link() const;

  /*!
   * @brief This function returns a reference to member child_link
   * @return Reference to member child_link
   */
  eProsima_user_DllExport std::string& child_link();

  /*!
   * @brief This function copies the value in member origin
   * @param _origin New value to be copied in member origin
   */
  eProsima_user_DllExport void origin(
      const booster_interface::msg::Origin& _origin);

  /*!
   * @brief This function moves the value in member origin
   * @param _origin New value to be moved in member origin
   */
  eProsima_user_DllExport void origin(booster_interface::msg::Origin&& _origin);

  /*!
   * @brief This function returns a constant reference to member origin
   * @return Constant reference to member origin
   */
  eProsima_user_DllExport const booster_interface::msg::Origin& origin() const;

  /*!
   * @brief This function returns a reference to member origin
   * @return Reference to member origin
   */
  eProsima_user_DllExport booster_interface::msg::Origin& origin();

  /*!
   * @brief This function copies the value in member axis
   * @param _axis New value to be copied in member axis
   */
  eProsima_user_DllExport void axis(const geometry_msgs::msg::Vector3& _axis);

  /*!
   * @brief This function moves the value in member axis
   * @param _axis New value to be moved in member axis
   */
  eProsima_user_DllExport void axis(geometry_msgs::msg::Vector3&& _axis);

  /*!
   * @brief This function returns a constant reference to member axis
   * @return Constant reference to member axis
   */
  eProsima_user_DllExport const geometry_msgs::msg::Vector3& axis() const;

  /*!
   * @brief This function returns a reference to member axis
   * @return Reference to member axis
   */
  eProsima_user_DllExport geometry_msgs::msg::Vector3& axis();

  /*!
   * @brief This function copies the value in member limit
   * @param _limit New value to be copied in member limit
   */
  eProsima_user_DllExport void limit(
      const booster_interface::msg::JointLimit& _limit);

  /*!
   * @brief This function moves the value in member limit
   * @param _limit New value to be moved in member limit
   */
  eProsima_user_DllExport void limit(
      booster_interface::msg::JointLimit&& _limit);

  /*!
   * @brief This function returns a constant reference to member limit
   * @return Constant reference to member limit
   */
  eProsima_user_DllExport const booster_interface::msg::JointLimit& limit()
      const;

  /*!
   * @brief This function returns a reference to member limit
   * @return Reference to member limit
   */
  eProsima_user_DllExport booster_interface::msg::JointLimit& limit();

 private:
  std::string m_name;
  booster_interface::msg::JointType m_type{
      booster_interface::msg::JOINT_TYPE_FIXED};
  std::string m_parent_link;
  std::string m_child_link;
  booster_interface::msg::Origin m_origin;
  geometry_msgs::msg::Vector3 m_axis;
  booster_interface::msg::JointLimit m_limit;

 public:
 public:
  typedef Joint DdsTopicMessageType;

  eProsima_user_DllExport Joint();

  eProsima_user_DllExport ~Joint() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure RobotModel defined by the user in
 * the IDL file.
 * @ingroup RobotModel
 */
class RobotModel : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::RobotModel that
   * will be copied.
   */
  eProsima_user_DllExport RobotModel(const RobotModel& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::RobotModel that
   * will be copied.
   */
  eProsima_user_DllExport RobotModel(RobotModel&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::RobotModel that
   * will be copied.
   */
  eProsima_user_DllExport RobotModel& operator=(const RobotModel& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::RobotModel that
   * will be copied.
   */
  eProsima_user_DllExport RobotModel& operator=(RobotModel&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::RobotModel object to compare.
   */
  eProsima_user_DllExport bool operator==(const RobotModel& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::RobotModel object to compare.
   */
  eProsima_user_DllExport bool operator!=(const RobotModel& x) const;

  /*!
   * @brief This function copies the value in member root_link
   * @param _root_link New value to be copied in member root_link
   */
  eProsima_user_DllExport void root_link(const std::string& _root_link);

  /*!
   * @brief This function moves the value in member root_link
   * @param _root_link New value to be moved in member root_link
   */
  eProsima_user_DllExport void root_link(std::string&& _root_link);

  /*!
   * @brief This function returns a constant reference to member root_link
   * @return Constant reference to member root_link
   */
  eProsima_user_DllExport const std::string& root_link() const;

  /*!
   * @brief This function returns a reference to member root_link
   * @return Reference to member root_link
   */
  eProsima_user_DllExport std::string& root_link();

  /*!
   * @brief This function copies the value in member links
   * @param _links New value to be copied in member links
   */
  eProsima_user_DllExport void links(
      const std::vector<booster_interface::msg::Link>& _links);

  /*!
   * @brief This function moves the value in member links
   * @param _links New value to be moved in member links
   */
  eProsima_user_DllExport void links(
      std::vector<booster_interface::msg::Link>&& _links);

  /*!
   * @brief This function returns a constant reference to member links
   * @return Constant reference to member links
   */
  eProsima_user_DllExport const std::vector<booster_interface::msg::Link>&
  links() const;

  /*!
   * @brief This function returns a reference to member links
   * @return Reference to member links
   */
  eProsima_user_DllExport std::vector<booster_interface::msg::Link>& links();

  /*!
   * @brief This function copies the value in member joints
   * @param _joints New value to be copied in member joints
   */
  eProsima_user_DllExport void joints(
      const std::vector<booster_interface::msg::Joint>& _joints);

  /*!
   * @brief This function moves the value in member joints
   * @param _joints New value to be moved in member joints
   */
  eProsima_user_DllExport void joints(
      std::vector<booster_interface::msg::Joint>&& _joints);

  /*!
   * @brief This function returns a constant reference to member joints
   * @return Constant reference to member joints
   */
  eProsima_user_DllExport const std::vector<booster_interface::msg::Joint>&
  joints() const;

  /*!
   * @brief This function returns a reference to member joints
   * @return Reference to member joints
   */
  eProsima_user_DllExport std::vector<booster_interface::msg::Joint>& joints();

 private:
  std::string m_root_link;
  std::vector<booster_interface::msg::Link> m_links;
  std::vector<booster_interface::msg::Joint> m_joints;

 public:
 public:
  typedef RobotModel DdsTopicMessageType;

  eProsima_user_DllExport RobotModel();

  eProsima_user_DllExport ~RobotModel() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_ROBOTMODEL_H_
