// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Camera.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_CAMERA_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_CAMERA_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <booster_fastdds/fastcdr/cdr/fixed_size_string.hpp>
#include <booster_fastdds/fastcdr/xcdr/external.hpp>
#include <booster_fastdds/fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <booster_fastdds/fastdds/rtps/common/InstanceHandle.h>
#include <booster_fastdds/fastdds/rtps/common/SerializedPayload.h>
#include <booster_fastdds/fastrtps/utils/md5.h>

#include <booster_fastdds/fastdds/dds/core/policy/QosPolicies.hpp>
#include <booster_fastdds/fastdds/dds/topic/TopicDataType.hpp>

#include "Camera.h"

#if !defined(BOOSTER_FASTDDS_GEN_API_VER) || (BOOSTER_FASTDDS_GEN_API_VER != 2)
#error \
    Generated Camera is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // BOOSTER_FASTDDS_GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#include "../geometry_msgs/Point.h"
#include "../geometry_msgs/Vector3.h"
#include "../sensor_msgs/CameraInfo.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CAMERA_SOURCE)
#define CAMERA_DllAPI __declspec(dllexport)
#else
#define CAMERA_DllAPI __declspec(dllimport)
#endif  // CAMERA_SOURCE
#else
#define CAMERA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CAMERA_DllAPI
#endif  // _WIN32

namespace booster_eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace booster_eprosima

namespace booster_interface {

namespace msg {

/*!
 * @brief This class represents the enumeration CameraModel defined by the user
 * in the IDL file.
 * @ingroup Camera
 */
enum CameraModel : uint32_t {
  CAMERA_Model_UNKNOWN,
  CAMERA_Model_REALSENSE_D455,
  CAMERA_Model_ZED_2I,
  CAMERA_Model_ORBBEC_GEMINI_335L,
  CAMERA_Model_BOOSTER_MIPI
};
/*!
 * @brief This class represents the enumeration CameraConnectionState defined by
 * the user in the IDL file.
 * @ingroup Camera
 */
enum CameraConnectionState : uint32_t {
  CAMERA_CONNECTION_UNKNOWN,
  CAMERA_CONNECTED,
  CAMERA_CONNECTION_LOST
};
/*!
 * @brief This class represents the enumeration CameraPos defined by the user in
 * the IDL file.
 * @ingroup Camera
 */
enum CameraPos : uint32_t {
  CAMERA_POS_UNKNOWN,
  CAMERA_POS_HEAD,
  CAMERA_POS_LEFT_HAND,
  CAMERA_POS_RIGHT_HAND,
  CAMERA_POS_WAIST
};
/*!
 * @brief This class represents the enumeration CameraPixelFormat defined by the
 * user in the IDL file.
 * @ingroup Camera
 */
enum CameraPixelFormat : uint32_t {
  CAMERA_PIXEL_FORMAT_UNKNOWN,
  CAMERA_PIXEL_FORMAT_RGB8,
  CAMERA_PIXEL_FORMAT_BGR8,
  CAMERA_PIXEL_FORMAT_YUV422,
  CAMERA_PIXEL_FORMAT_JPEG,
  CAMERA_PIXEL_FORMAT_NV12
};
/*!
 * @brief This class represents the enumeration DepthPixelFormat defined by the
 * user in the IDL file.
 * @ingroup Camera
 */
enum DepthPixelFormat : uint32_t {
  DEPTH_PIXEL_FORMAT_UNKNOWN,
  DEPTH_PIXEL_FORMAT_UINT16,
  DEPTH_PIXEL_FORMAT_FLOAT32
};

/*!
 * @brief This class represents the structure CameraTopic defined by the user in
 * the IDL file.
 * @ingroup Camera
 */
class CameraTopic : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::CameraTopic that
   * will be copied.
   */
  eProsima_user_DllExport CameraTopic(const CameraTopic& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::CameraTopic that
   * will be copied.
   */
  eProsima_user_DllExport CameraTopic(CameraTopic&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::CameraTopic that
   * will be copied.
   */
  eProsima_user_DllExport CameraTopic& operator=(const CameraTopic& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::CameraTopic that
   * will be copied.
   */
  eProsima_user_DllExport CameraTopic& operator=(CameraTopic&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::CameraTopic object to compare.
   */
  eProsima_user_DllExport bool operator==(const CameraTopic& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::CameraTopic object to compare.
   */
  eProsima_user_DllExport bool operator!=(const CameraTopic& x) const;

  /*!
   * @brief This function copies the value in member topics
   * @param _topics New value to be copied in member topics
   */
  eProsima_user_DllExport void topics(const std::vector<std::string>& _topics);

  /*!
   * @brief This function moves the value in member topics
   * @param _topics New value to be moved in member topics
   */
  eProsima_user_DllExport void topics(std::vector<std::string>&& _topics);

  /*!
   * @brief This function returns a constant reference to member topics
   * @return Constant reference to member topics
   */
  eProsima_user_DllExport const std::vector<std::string>& topics() const;

  /*!
   * @brief This function returns a reference to member topics
   * @return Reference to member topics
   */
  eProsima_user_DllExport std::vector<std::string>& topics();

 private:
  std::vector<std::string> m_topics;

 public:
 public:
  typedef CameraTopic type;

  eProsima_user_DllExport CameraTopic();

  eProsima_user_DllExport ~CameraTopic() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure CameraExtrinsics defined by the
 * user in the IDL file.
 * @ingroup Camera
 */
class CameraExtrinsics : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::CameraExtrinsics
   * that will be copied.
   */
  eProsima_user_DllExport CameraExtrinsics(const CameraExtrinsics& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::CameraExtrinsics
   * that will be copied.
   */
  eProsima_user_DllExport CameraExtrinsics(CameraExtrinsics&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::CameraExtrinsics
   * that will be copied.
   */
  eProsima_user_DllExport CameraExtrinsics& operator=(
      const CameraExtrinsics& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::CameraExtrinsics
   * that will be copied.
   */
  eProsima_user_DllExport CameraExtrinsics& operator=(
      CameraExtrinsics&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::CameraExtrinsics object to compare.
   */
  eProsima_user_DllExport bool operator==(const CameraExtrinsics& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::CameraExtrinsics object to compare.
   */
  eProsima_user_DllExport bool operator!=(const CameraExtrinsics& x) const;

  /*!
   * @brief This function copies the value in member parent_frame
   * @param _parent_frame New value to be copied in member parent_frame
   */
  eProsima_user_DllExport void parent_frame(const std::string& _parent_frame);

  /*!
   * @brief This function moves the value in member parent_frame
   * @param _parent_frame New value to be moved in member parent_frame
   */
  eProsima_user_DllExport void parent_frame(std::string&& _parent_frame);

  /*!
   * @brief This function returns a constant reference to member parent_frame
   * @return Constant reference to member parent_frame
   */
  eProsima_user_DllExport const std::string& parent_frame() const;

  /*!
   * @brief This function returns a reference to member parent_frame
   * @return Reference to member parent_frame
   */
  eProsima_user_DllExport std::string& parent_frame();

  /*!
   * @brief This function copies the value in member xyz
   * @param _xyz New value to be copied in member xyz
   */
  eProsima_user_DllExport void xyz(const geometry_msgs::msg::Point& _xyz);

  /*!
   * @brief This function moves the value in member xyz
   * @param _xyz New value to be moved in member xyz
   */
  eProsima_user_DllExport void xyz(geometry_msgs::msg::Point&& _xyz);

  /*!
   * @brief This function returns a constant reference to member xyz
   * @return Constant reference to member xyz
   */
  eProsima_user_DllExport const geometry_msgs::msg::Point& xyz() const;

  /*!
   * @brief This function returns a reference to member xyz
   * @return Reference to member xyz
   */
  eProsima_user_DllExport geometry_msgs::msg::Point& xyz();

  /*!
   * @brief This function copies the value in member rpy
   * @param _rpy New value to be copied in member rpy
   */
  eProsima_user_DllExport void rpy(const geometry_msgs::msg::Vector3& _rpy);

  /*!
   * @brief This function moves the value in member rpy
   * @param _rpy New value to be moved in member rpy
   */
  eProsima_user_DllExport void rpy(geometry_msgs::msg::Vector3&& _rpy);

  /*!
   * @brief This function returns a constant reference to member rpy
   * @return Constant reference to member rpy
   */
  eProsima_user_DllExport const geometry_msgs::msg::Vector3& rpy() const;

  /*!
   * @brief This function returns a reference to member rpy
   * @return Reference to member rpy
   */
  eProsima_user_DllExport geometry_msgs::msg::Vector3& rpy();

 private:
  std::string m_parent_frame;
  geometry_msgs::msg::Point m_xyz;
  geometry_msgs::msg::Vector3 m_rpy;

 public:
 public:
  typedef CameraExtrinsics type;

  eProsima_user_DllExport CameraExtrinsics();

  eProsima_user_DllExport ~CameraExtrinsics() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure CameraIntrinsics defined by the
 * user in the IDL file.
 * @ingroup Camera
 */
class CameraIntrinsics : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::CameraIntrinsics
   * that will be copied.
   */
  eProsima_user_DllExport CameraIntrinsics(const CameraIntrinsics& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::CameraIntrinsics
   * that will be copied.
   */
  eProsima_user_DllExport CameraIntrinsics(CameraIntrinsics&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::CameraIntrinsics
   * that will be copied.
   */
  eProsima_user_DllExport CameraIntrinsics& operator=(
      const CameraIntrinsics& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::CameraIntrinsics
   * that will be copied.
   */
  eProsima_user_DllExport CameraIntrinsics& operator=(
      CameraIntrinsics&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::CameraIntrinsics object to compare.
   */
  eProsima_user_DllExport bool operator==(const CameraIntrinsics& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::CameraIntrinsics object to compare.
   */
  eProsima_user_DllExport bool operator!=(const CameraIntrinsics& x) const;

  /*!
   * @brief This function sets a value in member fx
   * @param _fx New value for member fx
   */
  eProsima_user_DllExport void fx(double _fx);

  /*!
   * @brief This function returns the value of member fx
   * @return Value of member fx
   */
  eProsima_user_DllExport double fx() const;

  /*!
   * @brief This function returns a reference to member fx
   * @return Reference to member fx
   */
  eProsima_user_DllExport double& fx();

  /*!
   * @brief This function sets a value in member fy
   * @param _fy New value for member fy
   */
  eProsima_user_DllExport void fy(double _fy);

  /*!
   * @brief This function returns the value of member fy
   * @return Value of member fy
   */
  eProsima_user_DllExport double fy() const;

  /*!
   * @brief This function returns a reference to member fy
   * @return Reference to member fy
   */
  eProsima_user_DllExport double& fy();

  /*!
   * @brief This function sets a value in member cx
   * @param _cx New value for member cx
   */
  eProsima_user_DllExport void cx(double _cx);

  /*!
   * @brief This function returns the value of member cx
   * @return Value of member cx
   */
  eProsima_user_DllExport double cx() const;

  /*!
   * @brief This function returns a reference to member cx
   * @return Reference to member cx
   */
  eProsima_user_DllExport double& cx();

  /*!
   * @brief This function sets a value in member cy
   * @param _cy New value for member cy
   */
  eProsima_user_DllExport void cy(double _cy);

  /*!
   * @brief This function returns the value of member cy
   * @return Value of member cy
   */
  eProsima_user_DllExport double cy() const;

  /*!
   * @brief This function returns a reference to member cy
   * @return Reference to member cy
   */
  eProsima_user_DllExport double& cy();

 private:
  double m_fx{0.0};
  double m_fy{0.0};
  double m_cx{0.0};
  double m_cy{0.0};

 public:
 public:
  typedef CameraIntrinsics type;

  eProsima_user_DllExport CameraIntrinsics();

  eProsima_user_DllExport ~CameraIntrinsics() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure VideoStreamEncoding defined by the
 * user in the IDL file.
 * @ingroup Camera
 */
class VideoStreamEncoding : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object
   * booster_interface::msg::VideoStreamEncoding that will be copied.
   */
  eProsima_user_DllExport VideoStreamEncoding(const VideoStreamEncoding& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object
   * booster_interface::msg::VideoStreamEncoding that will be copied.
   */
  eProsima_user_DllExport VideoStreamEncoding(VideoStreamEncoding&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object
   * booster_interface::msg::VideoStreamEncoding that will be copied.
   */
  eProsima_user_DllExport VideoStreamEncoding& operator=(
      const VideoStreamEncoding& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object
   * booster_interface::msg::VideoStreamEncoding that will be copied.
   */
  eProsima_user_DllExport VideoStreamEncoding& operator=(
      VideoStreamEncoding&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::VideoStreamEncoding object to compare.
   */
  eProsima_user_DllExport bool operator==(const VideoStreamEncoding& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::VideoStreamEncoding object to compare.
   */
  eProsima_user_DllExport bool operator!=(const VideoStreamEncoding& x) const;

  /*!
   * @brief This function sets a value in member width
   * @param _width New value for member width
   */
  eProsima_user_DllExport void width(uint32_t _width);

  /*!
   * @brief This function returns the value of member width
   * @return Value of member width
   */
  eProsima_user_DllExport uint32_t width() const;

  /*!
   * @brief This function returns a reference to member width
   * @return Reference to member width
   */
  eProsima_user_DllExport uint32_t& width();

  /*!
   * @brief This function sets a value in member height
   * @param _height New value for member height
   */
  eProsima_user_DllExport void height(uint32_t _height);

  /*!
   * @brief This function returns the value of member height
   * @return Value of member height
   */
  eProsima_user_DllExport uint32_t height() const;

  /*!
   * @brief This function returns a reference to member height
   * @return Reference to member height
   */
  eProsima_user_DllExport uint32_t& height();

  /*!
   * @brief This function sets a value in member format
   * @param _format New value for member format
   */
  eProsima_user_DllExport void format(
      booster_interface::msg::CameraPixelFormat _format);

  /*!
   * @brief This function returns the value of member format
   * @return Value of member format
   */
  eProsima_user_DllExport booster_interface::msg::CameraPixelFormat format()
      const;

  /*!
   * @brief This function returns a reference to member format
   * @return Reference to member format
   */
  eProsima_user_DllExport booster_interface::msg::CameraPixelFormat& format();

  /*!
   * @brief This function sets a value in member bitrate_bps
   * @param _bitrate_bps New value for member bitrate_bps
   */
  eProsima_user_DllExport void bitrate_bps(uint32_t _bitrate_bps);

  /*!
   * @brief This function returns the value of member bitrate_bps
   * @return Value of member bitrate_bps
   */
  eProsima_user_DllExport uint32_t bitrate_bps() const;

  /*!
   * @brief This function returns a reference to member bitrate_bps
   * @return Reference to member bitrate_bps
   */
  eProsima_user_DllExport uint32_t& bitrate_bps();

 private:
  uint32_t m_width{0};
  uint32_t m_height{0};
  booster_interface::msg::CameraPixelFormat m_format{
      booster_interface::msg::CAMERA_PIXEL_FORMAT_UNKNOWN};
  uint32_t m_bitrate_bps{0};

 public:
 public:
  typedef VideoStreamEncoding type;

  eProsima_user_DllExport VideoStreamEncoding();

  eProsima_user_DllExport ~VideoStreamEncoding() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure DepthStreamEncoding defined by the
 * user in the IDL file.
 * @ingroup Camera
 */
class DepthStreamEncoding : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object
   * booster_interface::msg::DepthStreamEncoding that will be copied.
   */
  eProsima_user_DllExport DepthStreamEncoding(const DepthStreamEncoding& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object
   * booster_interface::msg::DepthStreamEncoding that will be copied.
   */
  eProsima_user_DllExport DepthStreamEncoding(DepthStreamEncoding&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object
   * booster_interface::msg::DepthStreamEncoding that will be copied.
   */
  eProsima_user_DllExport DepthStreamEncoding& operator=(
      const DepthStreamEncoding& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object
   * booster_interface::msg::DepthStreamEncoding that will be copied.
   */
  eProsima_user_DllExport DepthStreamEncoding& operator=(
      DepthStreamEncoding&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::DepthStreamEncoding object to compare.
   */
  eProsima_user_DllExport bool operator==(const DepthStreamEncoding& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::DepthStreamEncoding object to compare.
   */
  eProsima_user_DllExport bool operator!=(const DepthStreamEncoding& x) const;

  /*!
   * @brief This function sets a value in member width
   * @param _width New value for member width
   */
  eProsima_user_DllExport void width(uint32_t _width);

  /*!
   * @brief This function returns the value of member width
   * @return Value of member width
   */
  eProsima_user_DllExport uint32_t width() const;

  /*!
   * @brief This function returns a reference to member width
   * @return Reference to member width
   */
  eProsima_user_DllExport uint32_t& width();

  /*!
   * @brief This function sets a value in member height
   * @param _height New value for member height
   */
  eProsima_user_DllExport void height(uint32_t _height);

  /*!
   * @brief This function returns the value of member height
   * @return Value of member height
   */
  eProsima_user_DllExport uint32_t height() const;

  /*!
   * @brief This function returns a reference to member height
   * @return Reference to member height
   */
  eProsima_user_DllExport uint32_t& height();

  /*!
   * @brief This function sets a value in member format
   * @param _format New value for member format
   */
  eProsima_user_DllExport void format(
      booster_interface::msg::DepthPixelFormat _format);

  /*!
   * @brief This function returns the value of member format
   * @return Value of member format
   */
  eProsima_user_DllExport booster_interface::msg::DepthPixelFormat format()
      const;

  /*!
   * @brief This function returns a reference to member format
   * @return Reference to member format
   */
  eProsima_user_DllExport booster_interface::msg::DepthPixelFormat& format();

 private:
  uint32_t m_width{0};
  uint32_t m_height{0};
  booster_interface::msg::DepthPixelFormat m_format{
      booster_interface::msg::DEPTH_PIXEL_FORMAT_UNKNOWN};

 public:
 public:
  typedef DepthStreamEncoding type;

  eProsima_user_DllExport DepthStreamEncoding();

  eProsima_user_DllExport ~DepthStreamEncoding() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure Camera defined by the user in the
 * IDL file.
 * @ingroup Camera
 */
class Camera : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::Camera that will
   * be copied.
   */
  eProsima_user_DllExport Camera(const Camera& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::Camera that will
   * be copied.
   */
  eProsima_user_DllExport Camera(Camera&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::Camera that will
   * be copied.
   */
  eProsima_user_DllExport Camera& operator=(const Camera& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::Camera that will
   * be copied.
   */
  eProsima_user_DllExport Camera& operator=(Camera&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Camera object to compare.
   */
  eProsima_user_DllExport bool operator==(const Camera& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::Camera object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Camera& x) const;

  /*!
   * @brief This function copies the value in member name
   * @param _name New value to be copied in member name
   */
  eProsima_user_DllExport void name(const std::string& _name);

  /*!
   * @brief This function moves the value in member name
   * @param _name New value to be moved in member name
   */
  eProsima_user_DllExport void name(std::string&& _name);

  /*!
   * @brief This function returns a constant reference to member name
   * @return Constant reference to member name
   */
  eProsima_user_DllExport const std::string& name() const;

  /*!
   * @brief This function returns a reference to member name
   * @return Reference to member name
   */
  eProsima_user_DllExport std::string& name();

  /*!
   * @brief This function copies the value in member frame_id
   * @param _frame_id New value to be copied in member frame_id
   */
  eProsima_user_DllExport void frame_id(const std::string& _frame_id);

  /*!
   * @brief This function moves the value in member frame_id
   * @param _frame_id New value to be moved in member frame_id
   */
  eProsima_user_DllExport void frame_id(std::string&& _frame_id);

  /*!
   * @brief This function returns a constant reference to member frame_id
   * @return Constant reference to member frame_id
   */
  eProsima_user_DllExport const std::string& frame_id() const;

  /*!
   * @brief This function returns a reference to member frame_id
   * @return Reference to member frame_id
   */
  eProsima_user_DllExport std::string& frame_id();

  /*!
   * @brief This function copies the value in member serial_number
   * @param _serial_number New value to be copied in member serial_number
   */
  eProsima_user_DllExport void serial_number(const std::string& _serial_number);

  /*!
   * @brief This function moves the value in member serial_number
   * @param _serial_number New value to be moved in member serial_number
   */
  eProsima_user_DllExport void serial_number(std::string&& _serial_number);

  /*!
   * @brief This function returns a constant reference to member serial_number
   * @return Constant reference to member serial_number
   */
  eProsima_user_DllExport const std::string& serial_number() const;

  /*!
   * @brief This function returns a reference to member serial_number
   * @return Reference to member serial_number
   */
  eProsima_user_DllExport std::string& serial_number();

  /*!
   * @brief This function sets a value in member pos
   * @param _pos New value for member pos
   */
  eProsima_user_DllExport void pos(booster_interface::msg::CameraPos _pos);

  /*!
   * @brief This function returns the value of member pos
   * @return Value of member pos
   */
  eProsima_user_DllExport booster_interface::msg::CameraPos pos() const;

  /*!
   * @brief This function returns a reference to member pos
   * @return Reference to member pos
   */
  eProsima_user_DllExport booster_interface::msg::CameraPos& pos();

  /*!
   * @brief This function sets a value in member model
   * @param _model New value for member model
   */
  eProsima_user_DllExport void model(
      booster_interface::msg::CameraModel _model);

  /*!
   * @brief This function returns the value of member model
   * @return Value of member model
   */
  eProsima_user_DllExport booster_interface::msg::CameraModel model() const;

  /*!
   * @brief This function returns a reference to member model
   * @return Reference to member model
   */
  eProsima_user_DllExport booster_interface::msg::CameraModel& model();

  /*!
   * @brief This function sets a value in member state
   * @param _state New value for member state
   */
  eProsima_user_DllExport void state(
      booster_interface::msg::CameraConnectionState _state);

  /*!
   * @brief This function returns the value of member state
   * @return Value of member state
   */
  eProsima_user_DllExport booster_interface::msg::CameraConnectionState state()
      const;

  /*!
   * @brief This function returns a reference to member state
   * @return Reference to member state
   */
  eProsima_user_DllExport booster_interface::msg::CameraConnectionState&
  state();

  /*!
   * @brief This function copies the value in member topics
   * @param _topics New value to be copied in member topics
   */
  eProsima_user_DllExport void topics(
      const booster_interface::msg::CameraTopic& _topics);

  /*!
   * @brief This function moves the value in member topics
   * @param _topics New value to be moved in member topics
   */
  eProsima_user_DllExport void topics(
      booster_interface::msg::CameraTopic&& _topics);

  /*!
   * @brief This function returns a constant reference to member topics
   * @return Constant reference to member topics
   */
  eProsima_user_DllExport const booster_interface::msg::CameraTopic& topics()
      const;

  /*!
   * @brief This function returns a reference to member topics
   * @return Reference to member topics
   */
  eProsima_user_DllExport booster_interface::msg::CameraTopic& topics();

  /*!
   * @brief This function sets a value in member depth_scale
   * @param _depth_scale New value for member depth_scale
   */
  eProsima_user_DllExport void depth_scale(double _depth_scale);

  /*!
   * @brief This function returns the value of member depth_scale
   * @return Value of member depth_scale
   */
  eProsima_user_DllExport double depth_scale() const;

  /*!
   * @brief This function returns a reference to member depth_scale
   * @return Reference to member depth_scale
   */
  eProsima_user_DllExport double& depth_scale();

  /*!
   * @brief This function copies the value in member extrinsics
   * @param _extrinsics New value to be copied in member extrinsics
   */
  eProsima_user_DllExport void extrinsics(
      const booster_interface::msg::CameraExtrinsics& _extrinsics);

  /*!
   * @brief This function moves the value in member extrinsics
   * @param _extrinsics New value to be moved in member extrinsics
   */
  eProsima_user_DllExport void extrinsics(
      booster_interface::msg::CameraExtrinsics&& _extrinsics);

  /*!
   * @brief This function returns a constant reference to member extrinsics
   * @return Constant reference to member extrinsics
   */
  eProsima_user_DllExport const booster_interface::msg::CameraExtrinsics&
  extrinsics() const;

  /*!
   * @brief This function returns a reference to member extrinsics
   * @return Reference to member extrinsics
   */
  eProsima_user_DllExport booster_interface::msg::CameraExtrinsics&
  extrinsics();

  /*!
   * @brief This function copies the value in member color_encoding
   * @param _color_encoding New value to be copied in member color_encoding
   */
  eProsima_user_DllExport void color_encoding(
      const booster_interface::msg::VideoStreamEncoding& _color_encoding);

  /*!
   * @brief This function moves the value in member color_encoding
   * @param _color_encoding New value to be moved in member color_encoding
   */
  eProsima_user_DllExport void color_encoding(
      booster_interface::msg::VideoStreamEncoding&& _color_encoding);

  /*!
   * @brief This function returns a constant reference to member color_encoding
   * @return Constant reference to member color_encoding
   */
  eProsima_user_DllExport const booster_interface::msg::VideoStreamEncoding&
  color_encoding() const;

  /*!
   * @brief This function returns a reference to member color_encoding
   * @return Reference to member color_encoding
   */
  eProsima_user_DllExport booster_interface::msg::VideoStreamEncoding&
  color_encoding();

  /*!
   * @brief This function copies the value in member depth_encoding
   * @param _depth_encoding New value to be copied in member depth_encoding
   */
  eProsima_user_DllExport void depth_encoding(
      const booster_interface::msg::DepthStreamEncoding& _depth_encoding);

  /*!
   * @brief This function moves the value in member depth_encoding
   * @param _depth_encoding New value to be moved in member depth_encoding
   */
  eProsima_user_DllExport void depth_encoding(
      booster_interface::msg::DepthStreamEncoding&& _depth_encoding);

  /*!
   * @brief This function returns a constant reference to member depth_encoding
   * @return Constant reference to member depth_encoding
   */
  eProsima_user_DllExport const booster_interface::msg::DepthStreamEncoding&
  depth_encoding() const;

  /*!
   * @brief This function returns a reference to member depth_encoding
   * @return Reference to member depth_encoding
   */
  eProsima_user_DllExport booster_interface::msg::DepthStreamEncoding&
  depth_encoding();

 private:
  std::string m_name;
  std::string m_frame_id;
  std::string m_serial_number;
  booster_interface::msg::CameraPos m_pos{
      booster_interface::msg::CAMERA_POS_UNKNOWN};
  booster_interface::msg::CameraModel m_model{
      booster_interface::msg::CAMERA_Model_UNKNOWN};
  booster_interface::msg::CameraConnectionState m_state{
      booster_interface::msg::CAMERA_CONNECTION_UNKNOWN};
  booster_interface::msg::CameraTopic m_topics;
  double m_depth_scale{0.0};
  booster_interface::msg::CameraExtrinsics m_extrinsics;
  booster_interface::msg::VideoStreamEncoding m_color_encoding;
  booster_interface::msg::DepthStreamEncoding m_depth_encoding;

 public:
 public:
  typedef Camera type;

  eProsima_user_DllExport Camera();

  eProsima_user_DllExport ~Camera() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

/*!
 * @brief This class represents the structure CameraList defined by the user in
 * the IDL file.
 * @ingroup Camera
 */
class CameraList : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_interface::msg::CameraList that
   * will be copied.
   */
  eProsima_user_DllExport CameraList(const CameraList& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_interface::msg::CameraList that
   * will be copied.
   */
  eProsima_user_DllExport CameraList(CameraList&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_interface::msg::CameraList that
   * will be copied.
   */
  eProsima_user_DllExport CameraList& operator=(const CameraList& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_interface::msg::CameraList that
   * will be copied.
   */
  eProsima_user_DllExport CameraList& operator=(CameraList&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::CameraList object to compare.
   */
  eProsima_user_DllExport bool operator==(const CameraList& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_interface::msg::CameraList object to compare.
   */
  eProsima_user_DllExport bool operator!=(const CameraList& x) const;

  /*!
   * @brief This function copies the value in member cameras
   * @param _cameras New value to be copied in member cameras
   */
  eProsima_user_DllExport void cameras(
      const std::vector<booster_interface::msg::Camera>& _cameras);

  /*!
   * @brief This function moves the value in member cameras
   * @param _cameras New value to be moved in member cameras
   */
  eProsima_user_DllExport void cameras(
      std::vector<booster_interface::msg::Camera>&& _cameras);

  /*!
   * @brief This function returns a constant reference to member cameras
   * @return Constant reference to member cameras
   */
  eProsima_user_DllExport const std::vector<booster_interface::msg::Camera>&
  cameras() const;

  /*!
   * @brief This function returns a reference to member cameras
   * @return Reference to member cameras
   */
  eProsima_user_DllExport std::vector<booster_interface::msg::Camera>&
  cameras();

 private:
  std::vector<booster_interface::msg::Camera> m_cameras;

 public:
 public:
  typedef CameraList type;

  eProsima_user_DllExport CameraList();

  eProsima_user_DllExport ~CameraList() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace booster_interface

#endif  // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_CAMERA_H_
