// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BluetoothEventTopic.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_BLUETOOTHEVENTTOPIC_H_
#define _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_BLUETOOTHEVENTTOPIC_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <booster_fastdds/fastcdr/cdr/fixed_size_string.hpp>
#include <booster_fastdds/fastcdr/xcdr/external.hpp>
#include <booster_fastdds/fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <booster_fastdds/fastdds/rtps/common/InstanceHandle.h>
#include <booster_fastdds/fastdds/rtps/common/SerializedPayload.h>
#include <booster_fastdds/fastrtps/utils/md5.h>

#include <booster_fastdds/fastdds/dds/core/policy/QosPolicies.hpp>
#include <booster_fastdds/fastdds/dds/topic/TopicDataType.hpp>

#if !defined(BOOSTER_FASTDDS_GEN_API_VER) || (BOOSTER_FASTDDS_GEN_API_VER != 2)
#error \
    Generated BluetoothEventTopic is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // BOOSTER_FASTDDS_GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BLUETOOTHEVENTTOPIC_SOURCE)
#define BLUETOOTHEVENTTOPIC_DllAPI __declspec(dllexport)
#else
#define BLUETOOTHEVENTTOPIC_DllAPI __declspec(dllimport)
#endif  // BLUETOOTHEVENTTOPIC_SOURCE
#else
#define BLUETOOTHEVENTTOPIC_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BLUETOOTHEVENTTOPIC_DllAPI
#endif  // _WIN32

namespace booster_eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace booster_eprosima

namespace booster_msgs {

namespace audio {

/*!
 * @brief This class represents the structure BluetoothEventTopic defined by the
 * user in the IDL file.
 * @ingroup BluetoothEventTopic
 */
class BluetoothEventTopic : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object booster_msgs::audio::BluetoothEventTopic
   * that will be copied.
   */
  eProsima_user_DllExport BluetoothEventTopic(const BluetoothEventTopic& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object booster_msgs::audio::BluetoothEventTopic
   * that will be copied.
   */
  eProsima_user_DllExport BluetoothEventTopic(BluetoothEventTopic&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object booster_msgs::audio::BluetoothEventTopic
   * that will be copied.
   */
  eProsima_user_DllExport BluetoothEventTopic& operator=(
      const BluetoothEventTopic& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object booster_msgs::audio::BluetoothEventTopic
   * that will be copied.
   */
  eProsima_user_DllExport BluetoothEventTopic& operator=(
      BluetoothEventTopic&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::BluetoothEventTopic object to compare.
   */
  eProsima_user_DllExport bool operator==(const BluetoothEventTopic& x) const;

  /*!
   * @brief Comparison operator.
   * @param x booster_msgs::audio::BluetoothEventTopic object to compare.
   */
  eProsima_user_DllExport bool operator!=(const BluetoothEventTopic& x) const;

  /*!
   * @brief This function sets a value in member timestamp_ms
   * @param _timestamp_ms New value for member timestamp_ms
   */
  eProsima_user_DllExport void timestamp_ms(int64_t _timestamp_ms);

  /*!
   * @brief This function returns the value of member timestamp_ms
   * @return Value of member timestamp_ms
   */
  eProsima_user_DllExport int64_t timestamp_ms() const;

  /*!
   * @brief This function returns a reference to member timestamp_ms
   * @return Reference to member timestamp_ms
   */
  eProsima_user_DllExport int64_t& timestamp_ms();

  /*!
   * @brief This function copies the value in member event_type
   * @param _event_type New value to be copied in member event_type
   */
  eProsima_user_DllExport void event_type(const std::string& _event_type);

  /*!
   * @brief This function moves the value in member event_type
   * @param _event_type New value to be moved in member event_type
   */
  eProsima_user_DllExport void event_type(std::string&& _event_type);

  /*!
   * @brief This function returns a constant reference to member event_type
   * @return Constant reference to member event_type
   */
  eProsima_user_DllExport const std::string& event_type() const;

  /*!
   * @brief This function returns a reference to member event_type
   * @return Reference to member event_type
   */
  eProsima_user_DllExport std::string& event_type();

  /*!
   * @brief This function copies the value in member address
   * @param _address New value to be copied in member address
   */
  eProsima_user_DllExport void address(const std::string& _address);

  /*!
   * @brief This function moves the value in member address
   * @param _address New value to be moved in member address
   */
  eProsima_user_DllExport void address(std::string&& _address);

  /*!
   * @brief This function returns a constant reference to member address
   * @return Constant reference to member address
   */
  eProsima_user_DllExport const std::string& address() const;

  /*!
   * @brief This function returns a reference to member address
   * @return Reference to member address
   */
  eProsima_user_DllExport std::string& address();

  /*!
   * @brief This function copies the value in member payload_json
   * @param _payload_json New value to be copied in member payload_json
   */
  eProsima_user_DllExport void payload_json(const std::string& _payload_json);

  /*!
   * @brief This function moves the value in member payload_json
   * @param _payload_json New value to be moved in member payload_json
   */
  eProsima_user_DllExport void payload_json(std::string&& _payload_json);

  /*!
   * @brief This function returns a constant reference to member payload_json
   * @return Constant reference to member payload_json
   */
  eProsima_user_DllExport const std::string& payload_json() const;

  /*!
   * @brief This function returns a reference to member payload_json
   * @return Reference to member payload_json
   */
  eProsima_user_DllExport std::string& payload_json();

  /*!
   * @brief This function sets a value in member error_code
   * @param _error_code New value for member error_code
   */
  eProsima_user_DllExport void error_code(int32_t _error_code);

  /*!
   * @brief This function returns the value of member error_code
   * @return Value of member error_code
   */
  eProsima_user_DllExport int32_t error_code() const;

  /*!
   * @brief This function returns a reference to member error_code
   * @return Reference to member error_code
   */
  eProsima_user_DllExport int32_t& error_code();

 private:
  int64_t m_timestamp_ms{0};
  std::string m_event_type;
  std::string m_address;
  std::string m_payload_json;
  int32_t m_error_code{0};

 public:
  typedef BluetoothEventTopic type;

  eProsima_user_DllExport BluetoothEventTopic();

  eProsima_user_DllExport ~BluetoothEventTopic() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace audio

}  // namespace booster_msgs

#endif  // _FAST_DDS_GENERATED_BOOSTER_MSGS_AUDIO_BLUETOOTHEVENTTOPIC_H_
