// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VelocityStamped.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_VELOCITYSTAMPED_H_
#define _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_VELOCITYSTAMPED_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated VelocityStamped is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------


#include "Twist.h"
#include "Header.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(VELOCITYSTAMPED_SOURCE)
#define VELOCITYSTAMPED_DllAPI __declspec(dllexport)
#else
#define VELOCITYSTAMPED_DllAPI __declspec(dllimport)
#endif  // VELOCITYSTAMPED_SOURCE
#else
#define VELOCITYSTAMPED_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define VELOCITYSTAMPED_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace geometry_msgs {
namespace msg {

/*!
 * @brief This class represents the structure VelocityStamped defined by the user in the
 * IDL file.
 * @ingroup VelocityStamped
 */
class VelocityStamped : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object geometry_msgs::msg::VelocityStamped that will be copied.
   */
  eProsima_user_DllExport VelocityStamped(const VelocityStamped& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object geometry_msgs::msg::VelocityStamped that will be copied.
   */
  eProsima_user_DllExport VelocityStamped(VelocityStamped&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object geometry_msgs::msg::VelocityStamped that will be copied.
   */
  eProsima_user_DllExport VelocityStamped& operator=(const VelocityStamped& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object geometry_msgs::msg::VelocityStamped that will be copied.
   */
  eProsima_user_DllExport VelocityStamped& operator=(VelocityStamped&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x geometry_msgs::msg::VelocityStamped object to compare.
   */
  eProsima_user_DllExport bool operator==(const VelocityStamped& x) const;

  /*!
   * @brief Comparison operator.
   * @param x geometry_msgs::msg::VelocityStamped object to compare.
   */
  eProsima_user_DllExport bool operator!=(const VelocityStamped& x) const;

  /*!
   * @brief This function copies the value in member header
   * @param _header New value to be copied in member header
   */
  eProsima_user_DllExport void header(
      const std_msgs::msg::Header& _header);

  /*!
   * @brief This function moves the value in member header
   * @param _header New value to be moved in member header
   */
  eProsima_user_DllExport void header(std_msgs::msg::Header&& _header);

  /*!
   * @brief This function returns a constant reference to member header
   * @return Constant reference to member header
   */
  eProsima_user_DllExport const std_msgs::msg::Header& header() const;

  /*!
   * @brief This function returns a reference to member header
   * @return Reference to member header
   */
  eProsima_user_DllExport std_msgs::msg::Header& header();

  /*!
   * @brief This function copies the value in member body_frame_id
   * @param _body_frame_id New value to be copied in member body_frame_id
   */
  eProsima_user_DllExport void body_frame_id(const std::string& _body_frame_id);

  /*!
   * @brief This function moves the value in member body_frame_id
   * @param _body_frame_id New value to be moved in member body_frame_id
   */
  eProsima_user_DllExport void body_frame_id(std::string&& _body_frame_id);

  /*!
   * @brief This function returns a constant reference to member body_frame_id
   * @return Constant reference to member body_frame_id
   */
  eProsima_user_DllExport const std::string& body_frame_id() const;

  /*!
   * @brief This function returns a reference to member body_frame_id
   * @return Reference to member body_frame_id
   */
  eProsima_user_DllExport std::string& body_frame_id();

  /*!
   * @brief This function copies the value in member reference_frame_id
   * @param _reference_frame_id New value to be copied in member reference_frame_id
   */
  eProsima_user_DllExport void reference_frame_id(const std::string& _reference_frame_id);

  /*!
   * @brief This function moves the value in member reference_frame_id
   * @param _reference_frame_id New value to be moved in member reference_frame_id
   */
  eProsima_user_DllExport void reference_frame_id(std::string&& _reference_frame_id);

  /*!
   * @brief This function returns a constant reference to member reference_frame_id
   * @return Constant reference to member reference_frame_id
   */
  eProsima_user_DllExport const std::string& reference_frame_id() const;

  /*!
   * @brief This function returns a reference to member reference_frame_id
   * @return Reference to member reference_frame_id
   */
  eProsima_user_DllExport std::string& reference_frame_id();

  /*!
   * @brief This function copies the value in member velocity
   * @param _velocity New value to be copied in member velocity
   */
  eProsima_user_DllExport void velocity(
      const geometry_msgs::msg::Twist& _velocity);

  /*!
   * @brief This function moves the value in member velocity
   * @param _velocity New value to be moved in member velocity
   */
  eProsima_user_DllExport void velocity(geometry_msgs::msg::Twist&& _velocity);

  /*!
   * @brief This function returns a constant reference to member velocity
   * @return Constant reference to member velocity
   */
  eProsima_user_DllExport const geometry_msgs::msg::Twist& velocity() const;

  /*!
   * @brief This function returns a reference to member velocity
   * @return Reference to member velocity
   */
  eProsima_user_DllExport geometry_msgs::msg::Twist& velocity();

 private:
  std_msgs::msg::Header m_header;
  std::string m_body_frame_id;
  std::string m_reference_frame_id;
  geometry_msgs::msg::Twist m_velocity;

 public:
  typedef VelocityStamped type;

  eProsima_user_DllExport VelocityStamped();

  eProsima_user_DllExport ~VelocityStamped() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;

};

}  // namespace msg
}  // namespace geometry_msgs

#endif  // _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_VELOCITYSTAMPED_H_