// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file AccelWithCovariance.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_ACCELWITHCOVARIANCE_H_
#define _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_ACCELWITHCOVARIANCE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated AccelWithCovariance is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------


#include "Accel.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ACCELWITHCOVARIANCE_SOURCE)
#define ACCELWITHCOVARIANCE_DllAPI __declspec(dllexport)
#else
#define ACCELWITHCOVARIANCE_DllAPI __declspec(dllimport)
#endif  // ACCELWITHCOVARIANCE_SOURCE
#else
#define ACCELWITHCOVARIANCE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ACCELWITHCOVARIANCE_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace geometry_msgs {
namespace msg {

/*!
 * @brief This class represents the structure AccelWithCovariance defined by the user in the
 * IDL file.
 * @ingroup AccelWithCovariance
 */
class AccelWithCovariance : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object geometry_msgs::msg::AccelWithCovariance that will be copied.
   */
  eProsima_user_DllExport AccelWithCovariance(const AccelWithCovariance& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object geometry_msgs::msg::AccelWithCovariance that will be copied.
   */
  eProsima_user_DllExport AccelWithCovariance(AccelWithCovariance&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object geometry_msgs::msg::AccelWithCovariance that will be copied.
   */
  eProsima_user_DllExport AccelWithCovariance& operator=(const AccelWithCovariance& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object geometry_msgs::msg::AccelWithCovariance that will be copied.
   */
  eProsima_user_DllExport AccelWithCovariance& operator=(AccelWithCovariance&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x geometry_msgs::msg::AccelWithCovariance object to compare.
   */
  eProsima_user_DllExport bool operator==(const AccelWithCovariance& x) const;

  /*!
   * @brief Comparison operator.
   * @param x geometry_msgs::msg::AccelWithCovariance object to compare.
   */
  eProsima_user_DllExport bool operator!=(const AccelWithCovariance& x) const;

  /*!
   * @brief This function copies the value in member accel
   * @param _accel New value to be copied in member accel
   */
  eProsima_user_DllExport void accel(
      const geometry_msgs::msg::Accel& _accel);

  /*!
   * @brief This function moves the value in member accel
   * @param _accel New value to be moved in member accel
   */
  eProsima_user_DllExport void accel(geometry_msgs::msg::Accel&& _accel);

  /*!
   * @brief This function returns a constant reference to member accel
   * @return Constant reference to member accel
   */
  eProsima_user_DllExport const geometry_msgs::msg::Accel& accel() const;

  /*!
   * @brief This function returns a reference to member accel
   * @return Reference to member accel
   */
  eProsima_user_DllExport geometry_msgs::msg::Accel& accel();

  /*!
   * @brief This function copies the value in member covariance
   * @param _covariance New value to be copied in member covariance
   */
  eProsima_user_DllExport void covariance(
      const double__36& _covariance);

  /*!
   * @brief This function moves the value in member covariance
   * @param _covariance New value to be moved in member covariance
   */
  eProsima_user_DllExport void covariance(double__36&& _covariance);

  /*!
   * @brief This function returns a constant reference to member covariance
   * @return Constant reference to member covariance
   */
  eProsima_user_DllExport const double__36& covariance() const;

  /*!
   * @brief This function returns a reference to member covariance
   * @return Reference to member covariance
   */
  eProsima_user_DllExport double__36& covariance();

 private:
  geometry_msgs::msg::Accel m_accel;
  double__36 m_covariance;

 public:
  typedef AccelWithCovariance type;

  eProsima_user_DllExport AccelWithCovariance();

  eProsima_user_DllExport ~AccelWithCovariance() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return is_plain(eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    new (memory) AccelWithCovariance();
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;

};

}  // namespace msg
}  // namespace geometry_msgs

#endif  // _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_ACCELWITHCOVARIANCE_H_