// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PoseWithCovariance.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_POSEWITHCOVARIANCE_H_
#define _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_POSEWITHCOVARIANCE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <booster_fastdds/fastcdr/cdr/fixed_size_string.hpp>
#include <booster_fastdds/fastcdr/xcdr/external.hpp>
#include <booster_fastdds/fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <booster_fastdds/fastdds/rtps/common/InstanceHandle.h>
#include <booster_fastdds/fastdds/rtps/common/SerializedPayload.h>
#include <booster_fastdds/fastrtps/utils/md5.h>

#include <booster_fastdds/fastdds/dds/core/policy/QosPolicies.hpp>
#include <booster_fastdds/fastdds/dds/topic/TopicDataType.hpp>

#if !defined(BOOSTER_FASTDDS_GEN_API_VER) || (BOOSTER_FASTDDS_GEN_API_VER != 2)
#error \
    Generated PoseWithCovariance is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // BOOSTER_FASTDDS_GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#include "Pose.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(POSEWITHCOVARIANCE_SOURCE)
#define POSEWITHCOVARIANCE_DllAPI __declspec(dllexport)
#else
#define POSEWITHCOVARIANCE_DllAPI __declspec(dllimport)
#endif  // POSEWITHCOVARIANCE_SOURCE
#else
#define POSEWITHCOVARIANCE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define POSEWITHCOVARIANCE_DllAPI
#endif  // _WIN32

namespace booster_eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace booster_eprosima

namespace geometry_msgs {

namespace msg {

typedef std::array<double, 36> double__36;

/*!
 * @brief This class represents the structure PoseWithCovariance defined by the
 * user in the IDL file.
 * @ingroup PoseWithCovariance
 */
class PoseWithCovariance : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object geometry_msgs::msg::PoseWithCovariance
   * that will be copied.
   */
  eProsima_user_DllExport PoseWithCovariance(const PoseWithCovariance& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object geometry_msgs::msg::PoseWithCovariance
   * that will be copied.
   */
  eProsima_user_DllExport PoseWithCovariance(PoseWithCovariance&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object geometry_msgs::msg::PoseWithCovariance
   * that will be copied.
   */
  eProsima_user_DllExport PoseWithCovariance& operator=(
      const PoseWithCovariance& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object geometry_msgs::msg::PoseWithCovariance
   * that will be copied.
   */
  eProsima_user_DllExport PoseWithCovariance& operator=(
      PoseWithCovariance&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x geometry_msgs::msg::PoseWithCovariance object to compare.
   */
  eProsima_user_DllExport bool operator==(const PoseWithCovariance& x) const;

  /*!
   * @brief Comparison operator.
   * @param x geometry_msgs::msg::PoseWithCovariance object to compare.
   */
  eProsima_user_DllExport bool operator!=(const PoseWithCovariance& x) const;

  /*!
   * @brief This function copies the value in member pose
   * @param _pose New value to be copied in member pose
   */
  eProsima_user_DllExport void pose(const geometry_msgs::msg::Pose& _pose);

  /*!
   * @brief This function moves the value in member pose
   * @param _pose New value to be moved in member pose
   */
  eProsima_user_DllExport void pose(geometry_msgs::msg::Pose&& _pose);

  /*!
   * @brief This function returns a constant reference to member pose
   * @return Constant reference to member pose
   */
  eProsima_user_DllExport const geometry_msgs::msg::Pose& pose() const;

  /*!
   * @brief This function returns a reference to member pose
   * @return Reference to member pose
   */
  eProsima_user_DllExport geometry_msgs::msg::Pose& pose();

  /*!
   * @brief This function copies the value in member covariance
   * @param _covariance New value to be copied in member covariance
   */
  eProsima_user_DllExport void covariance(
      const geometry_msgs::msg::double__36& _covariance);

  /*!
   * @brief This function moves the value in member covariance
   * @param _covariance New value to be moved in member covariance
   */
  eProsima_user_DllExport void covariance(
      geometry_msgs::msg::double__36&& _covariance);

  /*!
   * @brief This function returns a constant reference to member covariance
   * @return Constant reference to member covariance
   */
  eProsima_user_DllExport const geometry_msgs::msg::double__36& covariance()
      const;

  /*!
   * @brief This function returns a reference to member covariance
   * @return Reference to member covariance
   */
  eProsima_user_DllExport geometry_msgs::msg::double__36& covariance();

 private:
  geometry_msgs::msg::Pose m_pose;
  geometry_msgs::msg::double__36 m_covariance{0.0};

 public:
  typedef PoseWithCovariance type;

  eProsima_user_DllExport PoseWithCovariance();

  eProsima_user_DllExport ~PoseWithCovariance() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace geometry_msgs

#endif  // _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_POSEWITHCOVARIANCE_H_
