// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Twist.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_TWIST_H_
#define _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_TWIST_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <booster_fastdds/fastcdr/cdr/fixed_size_string.hpp>
#include <booster_fastdds/fastcdr/xcdr/external.hpp>
#include <booster_fastdds/fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <booster_fastdds/fastdds/rtps/common/InstanceHandle.h>
#include <booster_fastdds/fastdds/rtps/common/SerializedPayload.h>
#include <booster_fastdds/fastrtps/utils/md5.h>

#include <booster_fastdds/fastdds/dds/core/policy/QosPolicies.hpp>
#include <booster_fastdds/fastdds/dds/topic/TopicDataType.hpp>

#if !defined(BOOSTER_FASTDDS_GEN_API_VER) || (BOOSTER_FASTDDS_GEN_API_VER != 2)
#error \
    Generated Twist is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // BOOSTER_FASTDDS_GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------

#include "Vector3.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TWIST_SOURCE)
#define TWIST_DllAPI __declspec(dllexport)
#else
#define TWIST_DllAPI __declspec(dllimport)
#endif  // TWIST_SOURCE
#else
#define TWIST_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TWIST_DllAPI
#endif  // _WIN32

namespace booster_eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace booster_eprosima

namespace geometry_msgs {

namespace msg {

/*!
 * @brief This class represents the structure Twist defined by the user in the
 * IDL file.
 * @ingroup Twist
 */
class Twist : public booster_eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object geometry_msgs::msg::Twist that will be
   * copied.
   */
  eProsima_user_DllExport Twist(const Twist& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object geometry_msgs::msg::Twist that will be
   * copied.
   */
  eProsima_user_DllExport Twist(Twist&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object geometry_msgs::msg::Twist that will be
   * copied.
   */
  eProsima_user_DllExport Twist& operator=(const Twist& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object geometry_msgs::msg::Twist that will be
   * copied.
   */
  eProsima_user_DllExport Twist& operator=(Twist&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x geometry_msgs::msg::Twist object to compare.
   */
  eProsima_user_DllExport bool operator==(const Twist& x) const;

  /*!
   * @brief Comparison operator.
   * @param x geometry_msgs::msg::Twist object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Twist& x) const;

  /*!
   * @brief This function copies the value in member linear
   * @param _linear New value to be copied in member linear
   */
  eProsima_user_DllExport void linear(
      const geometry_msgs::msg::Vector3& _linear);

  /*!
   * @brief This function moves the value in member linear
   * @param _linear New value to be moved in member linear
   */
  eProsima_user_DllExport void linear(geometry_msgs::msg::Vector3&& _linear);

  /*!
   * @brief This function returns a constant reference to member linear
   * @return Constant reference to member linear
   */
  eProsima_user_DllExport const geometry_msgs::msg::Vector3& linear() const;

  /*!
   * @brief This function returns a reference to member linear
   * @return Reference to member linear
   */
  eProsima_user_DllExport geometry_msgs::msg::Vector3& linear();

  /*!
   * @brief This function copies the value in member angular
   * @param _angular New value to be copied in member angular
   */
  eProsima_user_DllExport void angular(
      const geometry_msgs::msg::Vector3& _angular);

  /*!
   * @brief This function moves the value in member angular
   * @param _angular New value to be moved in member angular
   */
  eProsima_user_DllExport void angular(geometry_msgs::msg::Vector3&& _angular);

  /*!
   * @brief This function returns a constant reference to member angular
   * @return Constant reference to member angular
   */
  eProsima_user_DllExport const geometry_msgs::msg::Vector3& angular() const;

  /*!
   * @brief This function returns a reference to member angular
   * @return Reference to member angular
   */
  eProsima_user_DllExport geometry_msgs::msg::Vector3& angular();

 private:
  geometry_msgs::msg::Vector3 m_linear;
  geometry_msgs::msg::Vector3 m_angular;

 public:
  typedef Twist type;

  eProsima_user_DllExport Twist();

  eProsima_user_DllExport ~Twist() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      booster_eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, booster_eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, booster_eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      booster_eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // BOOSTER_FASTDDS_TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  BoosterFastddsMD5 m_md5;
  unsigned char* m_keyBuffer;
};

}  // namespace msg

}  // namespace geometry_msgs

#endif  // _FAST_DDS_GENERATED_GEOMETRY_MSGS_MSG_TWIST_H_
