// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BatteryState.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_BATTERYSTATE_CONSTANTS_BATTERYSTATE_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_BATTERYSTATE_CONSTANTS_BATTERYSTATE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated BatteryState is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------


#include "Header.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BATTERYSTATE_SOURCE)
#define BATTERYSTATE_DllAPI __declspec(dllexport)
#else
#define BATTERYSTATE_DllAPI __declspec(dllimport)
#endif  // BATTERYSTATE_SOURCE
#else
#define BATTERYSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BATTERYSTATE_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace sensor_msgs {
namespace msg {
namespace BatteryState_Constants {

/*!
 * @brief This class represents the structure BatteryState defined by the user in the
 * IDL file.
 * @ingroup BatteryState
 */
class BatteryState : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object sensor_msgs::msg::BatteryState_Constants::BatteryState that will be copied.
   */
  eProsima_user_DllExport BatteryState(const BatteryState& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object sensor_msgs::msg::BatteryState_Constants::BatteryState that will be copied.
   */
  eProsima_user_DllExport BatteryState(BatteryState&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object sensor_msgs::msg::BatteryState_Constants::BatteryState that will be copied.
   */
  eProsima_user_DllExport BatteryState& operator=(const BatteryState& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object sensor_msgs::msg::BatteryState_Constants::BatteryState that will be copied.
   */
  eProsima_user_DllExport BatteryState& operator=(BatteryState&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x sensor_msgs::msg::BatteryState_Constants::BatteryState object to compare.
   */
  eProsima_user_DllExport bool operator==(const BatteryState& x) const;

  /*!
   * @brief Comparison operator.
   * @param x sensor_msgs::msg::BatteryState_Constants::BatteryState object to compare.
   */
  eProsima_user_DllExport bool operator!=(const BatteryState& x) const;

  /*!
   * @brief This function copies the value in member header
   * @param _header New value to be copied in member header
   */
  eProsima_user_DllExport void header(
      const std_msgs::msg::Header& _header);

  /*!
   * @brief This function moves the value in member header
   * @param _header New value to be moved in member header
   */
  eProsima_user_DllExport void header(std_msgs::msg::Header&& _header);

  /*!
   * @brief This function returns a constant reference to member header
   * @return Constant reference to member header
   */
  eProsima_user_DllExport const std_msgs::msg::Header& header() const;

  /*!
   * @brief This function returns a reference to member header
   * @return Reference to member header
   */
  eProsima_user_DllExport std_msgs::msg::Header& header();

  /*!
   * @brief This function sets a value in member voltage
   * @param _voltage New value for member voltage
   */
  eProsima_user_DllExport void voltage(float _voltage);

  /*!
   * @brief This function returns the value of member voltage
   * @return Value of member voltage
   */
  eProsima_user_DllExport float voltage() const;

  /*!
   * @brief This function returns a reference to member voltage
   * @return Reference to member voltage
   */
  eProsima_user_DllExport float& voltage();

  /*!
   * @brief This function sets a value in member temperature
   * @param _temperature New value for member temperature
   */
  eProsima_user_DllExport void temperature(float _temperature);

  /*!
   * @brief This function returns the value of member temperature
   * @return Value of member temperature
   */
  eProsima_user_DllExport float temperature() const;

  /*!
   * @brief This function returns a reference to member temperature
   * @return Reference to member temperature
   */
  eProsima_user_DllExport float& temperature();

  /*!
   * @brief This function sets a value in member current
   * @param _current New value for member current
   */
  eProsima_user_DllExport void current(float _current);

  /*!
   * @brief This function returns the value of member current
   * @return Value of member current
   */
  eProsima_user_DllExport float current() const;

  /*!
   * @brief This function returns a reference to member current
   * @return Reference to member current
   */
  eProsima_user_DllExport float& current();

  /*!
   * @brief This function sets a value in member charge
   * @param _charge New value for member charge
   */
  eProsima_user_DllExport void charge(float _charge);

  /*!
   * @brief This function returns the value of member charge
   * @return Value of member charge
   */
  eProsima_user_DllExport float charge() const;

  /*!
   * @brief This function returns a reference to member charge
   * @return Reference to member charge
   */
  eProsima_user_DllExport float& charge();

  /*!
   * @brief This function sets a value in member capacity
   * @param _capacity New value for member capacity
   */
  eProsima_user_DllExport void capacity(float _capacity);

  /*!
   * @brief This function returns the value of member capacity
   * @return Value of member capacity
   */
  eProsima_user_DllExport float capacity() const;

  /*!
   * @brief This function returns a reference to member capacity
   * @return Reference to member capacity
   */
  eProsima_user_DllExport float& capacity();

  /*!
   * @brief This function sets a value in member design_capacity
   * @param _design_capacity New value for member design_capacity
   */
  eProsima_user_DllExport void design_capacity(float _design_capacity);

  /*!
   * @brief This function returns the value of member design_capacity
   * @return Value of member design_capacity
   */
  eProsima_user_DllExport float design_capacity() const;

  /*!
   * @brief This function returns a reference to member design_capacity
   * @return Reference to member design_capacity
   */
  eProsima_user_DllExport float& design_capacity();

  /*!
   * @brief This function sets a value in member percentage
   * @param _percentage New value for member percentage
   */
  eProsima_user_DllExport void percentage(float _percentage);

  /*!
   * @brief This function returns the value of member percentage
   * @return Value of member percentage
   */
  eProsima_user_DllExport float percentage() const;

  /*!
   * @brief This function returns a reference to member percentage
   * @return Reference to member percentage
   */
  eProsima_user_DllExport float& percentage();

  /*!
   * @brief This function sets a value in member power_supply_status
   * @param _power_supply_status New value for member power_supply_status
   */
  eProsima_user_DllExport void power_supply_status(uint8 _power_supply_status);

  /*!
   * @brief This function returns the value of member power_supply_status
   * @return Value of member power_supply_status
   */
  eProsima_user_DllExport uint8 power_supply_status() const;

  /*!
   * @brief This function returns a reference to member power_supply_status
   * @return Reference to member power_supply_status
   */
  eProsima_user_DllExport uint8& power_supply_status();

  /*!
   * @brief This function sets a value in member power_supply_health
   * @param _power_supply_health New value for member power_supply_health
   */
  eProsima_user_DllExport void power_supply_health(uint8 _power_supply_health);

  /*!
   * @brief This function returns the value of member power_supply_health
   * @return Value of member power_supply_health
   */
  eProsima_user_DllExport uint8 power_supply_health() const;

  /*!
   * @brief This function returns a reference to member power_supply_health
   * @return Reference to member power_supply_health
   */
  eProsima_user_DllExport uint8& power_supply_health();

  /*!
   * @brief This function sets a value in member power_supply_technology
   * @param _power_supply_technology New value for member power_supply_technology
   */
  eProsima_user_DllExport void power_supply_technology(uint8 _power_supply_technology);

  /*!
   * @brief This function returns the value of member power_supply_technology
   * @return Value of member power_supply_technology
   */
  eProsima_user_DllExport uint8 power_supply_technology() const;

  /*!
   * @brief This function returns a reference to member power_supply_technology
   * @return Reference to member power_supply_technology
   */
  eProsima_user_DllExport uint8& power_supply_technology();

  /*!
   * @brief This function sets a value in member present
   * @param _present New value for member present
   */
  eProsima_user_DllExport void present(boolean _present);

  /*!
   * @brief This function returns the value of member present
   * @return Value of member present
   */
  eProsima_user_DllExport boolean present() const;

  /*!
   * @brief This function returns a reference to member present
   * @return Reference to member present
   */
  eProsima_user_DllExport boolean& present();

  /*!
   * @brief This function copies the value in member location
   * @param _location New value to be copied in member location
   */
  eProsima_user_DllExport void location(const std::string& _location);

  /*!
   * @brief This function moves the value in member location
   * @param _location New value to be moved in member location
   */
  eProsima_user_DllExport void location(std::string&& _location);

  /*!
   * @brief This function returns a constant reference to member location
   * @return Constant reference to member location
   */
  eProsima_user_DllExport const std::string& location() const;

  /*!
   * @brief This function returns a reference to member location
   * @return Reference to member location
   */
  eProsima_user_DllExport std::string& location();

  /*!
   * @brief This function copies the value in member serial_number
   * @param _serial_number New value to be copied in member serial_number
   */
  eProsima_user_DllExport void serial_number(const std::string& _serial_number);

  /*!
   * @brief This function moves the value in member serial_number
   * @param _serial_number New value to be moved in member serial_number
   */
  eProsima_user_DllExport void serial_number(std::string&& _serial_number);

  /*!
   * @brief This function returns a constant reference to member serial_number
   * @return Constant reference to member serial_number
   */
  eProsima_user_DllExport const std::string& serial_number() const;

  /*!
   * @brief This function returns a reference to member serial_number
   * @return Reference to member serial_number
   */
  eProsima_user_DllExport std::string& serial_number();

 private:
  std_msgs::msg::Header m_header;
  float m_voltage;
  float m_temperature;
  float m_current;
  float m_charge;
  float m_capacity;
  float m_design_capacity;
  float m_percentage;
  uint8 m_power_supply_status;
  uint8 m_power_supply_health;
  uint8 m_power_supply_technology;
  boolean m_present;
  std::string m_location;
  std::string m_serial_number;

 public:
  typedef BatteryState type;

  eProsima_user_DllExport BatteryState();

  eProsima_user_DllExport ~BatteryState() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;

};

}  // namespace BatteryState_Constants
}  // namespace msg
}  // namespace sensor_msgs

#endif  // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_BATTERYSTATE_CONSTANTS_BATTERYSTATE_H_