// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LaserScan.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_LASERSCAN_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_LASERSCAN_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated LaserScan is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------


#include "Header.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LASERSCAN_SOURCE)
#define LASERSCAN_DllAPI __declspec(dllexport)
#else
#define LASERSCAN_DllAPI __declspec(dllimport)
#endif  // LASERSCAN_SOURCE
#else
#define LASERSCAN_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LASERSCAN_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace sensor_msgs {
namespace msg {

/*!
 * @brief This class represents the structure LaserScan defined by the user in the
 * IDL file.
 * @ingroup LaserScan
 */
class LaserScan : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object sensor_msgs::msg::LaserScan that will be copied.
   */
  eProsima_user_DllExport LaserScan(const LaserScan& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object sensor_msgs::msg::LaserScan that will be copied.
   */
  eProsima_user_DllExport LaserScan(LaserScan&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object sensor_msgs::msg::LaserScan that will be copied.
   */
  eProsima_user_DllExport LaserScan& operator=(const LaserScan& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object sensor_msgs::msg::LaserScan that will be copied.
   */
  eProsima_user_DllExport LaserScan& operator=(LaserScan&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x sensor_msgs::msg::LaserScan object to compare.
   */
  eProsima_user_DllExport bool operator==(const LaserScan& x) const;

  /*!
   * @brief Comparison operator.
   * @param x sensor_msgs::msg::LaserScan object to compare.
   */
  eProsima_user_DllExport bool operator!=(const LaserScan& x) const;

  /*!
   * @brief This function copies the value in member header
   * @param _header New value to be copied in member header
   */
  eProsima_user_DllExport void header(
      const std_msgs::msg::Header& _header);

  /*!
   * @brief This function moves the value in member header
   * @param _header New value to be moved in member header
   */
  eProsima_user_DllExport void header(std_msgs::msg::Header&& _header);

  /*!
   * @brief This function returns a constant reference to member header
   * @return Constant reference to member header
   */
  eProsima_user_DllExport const std_msgs::msg::Header& header() const;

  /*!
   * @brief This function returns a reference to member header
   * @return Reference to member header
   */
  eProsima_user_DllExport std_msgs::msg::Header& header();

  /*!
   * @brief This function sets a value in member angle_min
   * @param _angle_min New value for member angle_min
   */
  eProsima_user_DllExport void angle_min(float _angle_min);

  /*!
   * @brief This function returns the value of member angle_min
   * @return Value of member angle_min
   */
  eProsima_user_DllExport float angle_min() const;

  /*!
   * @brief This function returns a reference to member angle_min
   * @return Reference to member angle_min
   */
  eProsima_user_DllExport float& angle_min();

  /*!
   * @brief This function sets a value in member angle_max
   * @param _angle_max New value for member angle_max
   */
  eProsima_user_DllExport void angle_max(float _angle_max);

  /*!
   * @brief This function returns the value of member angle_max
   * @return Value of member angle_max
   */
  eProsima_user_DllExport float angle_max() const;

  /*!
   * @brief This function returns a reference to member angle_max
   * @return Reference to member angle_max
   */
  eProsima_user_DllExport float& angle_max();

  /*!
   * @brief This function sets a value in member angle_increment
   * @param _angle_increment New value for member angle_increment
   */
  eProsima_user_DllExport void angle_increment(float _angle_increment);

  /*!
   * @brief This function returns the value of member angle_increment
   * @return Value of member angle_increment
   */
  eProsima_user_DllExport float angle_increment() const;

  /*!
   * @brief This function returns a reference to member angle_increment
   * @return Reference to member angle_increment
   */
  eProsima_user_DllExport float& angle_increment();

  /*!
   * @brief This function sets a value in member time_increment
   * @param _time_increment New value for member time_increment
   */
  eProsima_user_DllExport void time_increment(float _time_increment);

  /*!
   * @brief This function returns the value of member time_increment
   * @return Value of member time_increment
   */
  eProsima_user_DllExport float time_increment() const;

  /*!
   * @brief This function returns a reference to member time_increment
   * @return Reference to member time_increment
   */
  eProsima_user_DllExport float& time_increment();

  /*!
   * @brief This function sets a value in member scan_time
   * @param _scan_time New value for member scan_time
   */
  eProsima_user_DllExport void scan_time(float _scan_time);

  /*!
   * @brief This function returns the value of member scan_time
   * @return Value of member scan_time
   */
  eProsima_user_DllExport float scan_time() const;

  /*!
   * @brief This function returns a reference to member scan_time
   * @return Reference to member scan_time
   */
  eProsima_user_DllExport float& scan_time();

  /*!
   * @brief This function sets a value in member range_min
   * @param _range_min New value for member range_min
   */
  eProsima_user_DllExport void range_min(float _range_min);

  /*!
   * @brief This function returns the value of member range_min
   * @return Value of member range_min
   */
  eProsima_user_DllExport float range_min() const;

  /*!
   * @brief This function returns a reference to member range_min
   * @return Reference to member range_min
   */
  eProsima_user_DllExport float& range_min();

  /*!
   * @brief This function sets a value in member range_max
   * @param _range_max New value for member range_max
   */
  eProsima_user_DllExport void range_max(float _range_max);

  /*!
   * @brief This function returns the value of member range_max
   * @return Value of member range_max
   */
  eProsima_user_DllExport float range_max() const;

  /*!
   * @brief This function returns a reference to member range_max
   * @return Reference to member range_max
   */
  eProsima_user_DllExport float& range_max();

 private:
  std_msgs::msg::Header m_header;
  float m_angle_min;
  float m_angle_max;
  float m_angle_increment;
  float m_time_increment;
  float m_scan_time;
  float m_range_min;
  float m_range_max;

 public:
  typedef LaserScan type;

  eProsima_user_DllExport LaserScan();

  eProsima_user_DllExport ~LaserScan() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return is_plain(eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    new (memory) LaserScan();
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;

};

}  // namespace msg
}  // namespace sensor_msgs

#endif  // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_LASERSCAN_H_