// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PointField.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_POINTFIELD_CONSTANTS_POINTFIELD_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_POINTFIELD_CONSTANTS_POINTFIELD_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated PointField is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(POINTFIELD_SOURCE)
#define POINTFIELD_DllAPI __declspec(dllexport)
#else
#define POINTFIELD_DllAPI __declspec(dllimport)
#endif  // POINTFIELD_SOURCE
#else
#define POINTFIELD_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define POINTFIELD_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace sensor_msgs {
namespace msg {
namespace PointField_Constants {

/*!
 * @brief This class represents the structure PointField defined by the user in the
 * IDL file.
 * @ingroup PointField
 */
class PointField : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object sensor_msgs::msg::PointField_Constants::PointField that will be copied.
   */
  eProsima_user_DllExport PointField(const PointField& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object sensor_msgs::msg::PointField_Constants::PointField that will be copied.
   */
  eProsima_user_DllExport PointField(PointField&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object sensor_msgs::msg::PointField_Constants::PointField that will be copied.
   */
  eProsima_user_DllExport PointField& operator=(const PointField& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object sensor_msgs::msg::PointField_Constants::PointField that will be copied.
   */
  eProsima_user_DllExport PointField& operator=(PointField&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x sensor_msgs::msg::PointField_Constants::PointField object to compare.
   */
  eProsima_user_DllExport bool operator==(const PointField& x) const;

  /*!
   * @brief Comparison operator.
   * @param x sensor_msgs::msg::PointField_Constants::PointField object to compare.
   */
  eProsima_user_DllExport bool operator!=(const PointField& x) const;

  /*!
   * @brief This function copies the value in member name
   * @param _name New value to be copied in member name
   */
  eProsima_user_DllExport void name(const std::string& _name);

  /*!
   * @brief This function moves the value in member name
   * @param _name New value to be moved in member name
   */
  eProsima_user_DllExport void name(std::string&& _name);

  /*!
   * @brief This function returns a constant reference to member name
   * @return Constant reference to member name
   */
  eProsima_user_DllExport const std::string& name() const;

  /*!
   * @brief This function returns a reference to member name
   * @return Reference to member name
   */
  eProsima_user_DllExport std::string& name();

  /*!
   * @brief This function sets a value in member offset
   * @param _offset New value for member offset
   */
  eProsima_user_DllExport void offset(uint32 _offset);

  /*!
   * @brief This function returns the value of member offset
   * @return Value of member offset
   */
  eProsima_user_DllExport uint32 offset() const;

  /*!
   * @brief This function returns a reference to member offset
   * @return Reference to member offset
   */
  eProsima_user_DllExport uint32& offset();

  /*!
   * @brief This function sets a value in member datatype
   * @param _datatype New value for member datatype
   */
  eProsima_user_DllExport void datatype(uint8 _datatype);

  /*!
   * @brief This function returns the value of member datatype
   * @return Value of member datatype
   */
  eProsima_user_DllExport uint8 datatype() const;

  /*!
   * @brief This function returns a reference to member datatype
   * @return Reference to member datatype
   */
  eProsima_user_DllExport uint8& datatype();

  /*!
   * @brief This function sets a value in member count
   * @param _count New value for member count
   */
  eProsima_user_DllExport void count(uint32 _count);

  /*!
   * @brief This function returns the value of member count
   * @return Value of member count
   */
  eProsima_user_DllExport uint32 count() const;

  /*!
   * @brief This function returns a reference to member count
   * @return Reference to member count
   */
  eProsima_user_DllExport uint32& count();

 private:
  std::string m_name;
  uint32 m_offset;
  uint8 m_datatype;
  uint32 m_count;

 public:
  typedef PointField type;

  eProsima_user_DllExport PointField();

  eProsima_user_DllExport ~PointField() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return false;
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    static_cast<void>(memory);
    return false;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;

};

}  // namespace PointField_Constants
}  // namespace msg
}  // namespace sensor_msgs

#endif  // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_POINTFIELD_CONSTANTS_POINTFIELD_H_