// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PointCloud2.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD2_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD2_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated PointCloud2 is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------


#include "PointField.h"
#include "Header.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(POINTCLOUD2_SOURCE)
#define POINTCLOUD2_DllAPI __declspec(dllexport)
#else
#define POINTCLOUD2_DllAPI __declspec(dllimport)
#endif  // POINTCLOUD2_SOURCE
#else
#define POINTCLOUD2_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define POINTCLOUD2_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace sensor_msgs {
namespace msg {

/*!
 * @brief This class represents the structure PointCloud2 defined by the user in the
 * IDL file.
 * @ingroup PointCloud2
 */
class PointCloud2 : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object sensor_msgs::msg::PointCloud2 that will be copied.
   */
  eProsima_user_DllExport PointCloud2(const PointCloud2& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object sensor_msgs::msg::PointCloud2 that will be copied.
   */
  eProsima_user_DllExport PointCloud2(PointCloud2&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object sensor_msgs::msg::PointCloud2 that will be copied.
   */
  eProsima_user_DllExport PointCloud2& operator=(const PointCloud2& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object sensor_msgs::msg::PointCloud2 that will be copied.
   */
  eProsima_user_DllExport PointCloud2& operator=(PointCloud2&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x sensor_msgs::msg::PointCloud2 object to compare.
   */
  eProsima_user_DllExport bool operator==(const PointCloud2& x) const;

  /*!
   * @brief Comparison operator.
   * @param x sensor_msgs::msg::PointCloud2 object to compare.
   */
  eProsima_user_DllExport bool operator!=(const PointCloud2& x) const;

  /*!
   * @brief This function copies the value in member header
   * @param _header New value to be copied in member header
   */
  eProsima_user_DllExport void header(
      const std_msgs::msg::Header& _header);

  /*!
   * @brief This function moves the value in member header
   * @param _header New value to be moved in member header
   */
  eProsima_user_DllExport void header(std_msgs::msg::Header&& _header);

  /*!
   * @brief This function returns a constant reference to member header
   * @return Constant reference to member header
   */
  eProsima_user_DllExport const std_msgs::msg::Header& header() const;

  /*!
   * @brief This function returns a reference to member header
   * @return Reference to member header
   */
  eProsima_user_DllExport std_msgs::msg::Header& header();

  /*!
   * @brief This function sets a value in member height
   * @param _height New value for member height
   */
  eProsima_user_DllExport void height(uint32 _height);

  /*!
   * @brief This function returns the value of member height
   * @return Value of member height
   */
  eProsima_user_DllExport uint32 height() const;

  /*!
   * @brief This function returns a reference to member height
   * @return Reference to member height
   */
  eProsima_user_DllExport uint32& height();

  /*!
   * @brief This function sets a value in member width
   * @param _width New value for member width
   */
  eProsima_user_DllExport void width(uint32 _width);

  /*!
   * @brief This function returns the value of member width
   * @return Value of member width
   */
  eProsima_user_DllExport uint32 width() const;

  /*!
   * @brief This function returns a reference to member width
   * @return Reference to member width
   */
  eProsima_user_DllExport uint32& width();

  /*!
   * @brief This function sets a value in member is_bigendian
   * @param _is_bigendian New value for member is_bigendian
   */
  eProsima_user_DllExport void is_bigendian(boolean _is_bigendian);

  /*!
   * @brief This function returns the value of member is_bigendian
   * @return Value of member is_bigendian
   */
  eProsima_user_DllExport boolean is_bigendian() const;

  /*!
   * @brief This function returns a reference to member is_bigendian
   * @return Reference to member is_bigendian
   */
  eProsima_user_DllExport boolean& is_bigendian();

  /*!
   * @brief This function sets a value in member point_step
   * @param _point_step New value for member point_step
   */
  eProsima_user_DllExport void point_step(uint32 _point_step);

  /*!
   * @brief This function returns the value of member point_step
   * @return Value of member point_step
   */
  eProsima_user_DllExport uint32 point_step() const;

  /*!
   * @brief This function returns a reference to member point_step
   * @return Reference to member point_step
   */
  eProsima_user_DllExport uint32& point_step();

  /*!
   * @brief This function sets a value in member row_step
   * @param _row_step New value for member row_step
   */
  eProsima_user_DllExport void row_step(uint32 _row_step);

  /*!
   * @brief This function returns the value of member row_step
   * @return Value of member row_step
   */
  eProsima_user_DllExport uint32 row_step() const;

  /*!
   * @brief This function returns a reference to member row_step
   * @return Reference to member row_step
   */
  eProsima_user_DllExport uint32& row_step();

  /*!
   * @brief This function sets a value in member is_dense
   * @param _is_dense New value for member is_dense
   */
  eProsima_user_DllExport void is_dense(boolean _is_dense);

  /*!
   * @brief This function returns the value of member is_dense
   * @return Value of member is_dense
   */
  eProsima_user_DllExport boolean is_dense() const;

  /*!
   * @brief This function returns a reference to member is_dense
   * @return Reference to member is_dense
   */
  eProsima_user_DllExport boolean& is_dense();

 private:
  std_msgs::msg::Header m_header;
  uint32 m_height;
  uint32 m_width;
  boolean m_is_bigendian;
  uint32 m_point_step;
  uint32 m_row_step;
  boolean m_is_dense;

 public:
  typedef PointCloud2 type;

  eProsima_user_DllExport PointCloud2();

  eProsima_user_DllExport ~PointCloud2() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return is_plain(eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    new (memory) PointCloud2();
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;

};

}  // namespace msg
}  // namespace sensor_msgs

#endif  // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_POINTCLOUD2_H_