// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Range.h
 * This header file contains the declaration of the described types in the IDL
 * file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_RANGE_CONSTANTS_RANGE_H_
#define _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_RANGE_CONSTANTS_RANGE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <map>
#include <string>
#include <vector>

// ------------------------------ Pub Sub Type Start
// ----------------------------
#include <fastdds/rtps/common/InstanceHandle.h>
#include <fastdds/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>

#include <fastdds/dds/core/policy/QosPolicies.hpp>
#include <fastdds/dds/topic/TopicDataType.hpp>

#if !defined(GEN_API_VER) || (GEN_API_VER != 2)
#error \
    Generated Range is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

// ------------------------------ Pub Sub Type End ----------------------------


#include "Header.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(RANGE_SOURCE)
#define RANGE_DllAPI __declspec(dllexport)
#else
#define RANGE_DllAPI __declspec(dllimport)
#endif  // RANGE_SOURCE
#else
#define RANGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define RANGE_DllAPI
#endif  // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
}  // namespace fastcdr
}  // namespace eprosima

namespace sensor_msgs {
namespace msg {
namespace Range_Constants {

/*!
 * @brief This class represents the structure Range defined by the user in the
 * IDL file.
 * @ingroup Range
 */
class Range : public eprosima::fastdds::dds::TopicDataType {
 public:
  /*!
   * @brief Copy constructor.
   * @param x Reference to the object sensor_msgs::msg::Range_Constants::Range that will be copied.
   */
  eProsima_user_DllExport Range(const Range& x);

  /*!
   * @brief Move constructor.
   * @param x Reference to the object sensor_msgs::msg::Range_Constants::Range that will be copied.
   */
  eProsima_user_DllExport Range(Range&& x) noexcept;

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object sensor_msgs::msg::Range_Constants::Range that will be copied.
   */
  eProsima_user_DllExport Range& operator=(const Range& x);

  /*!
   * @brief Move assignment.
   * @param x Reference to the object sensor_msgs::msg::Range_Constants::Range that will be copied.
   */
  eProsima_user_DllExport Range& operator=(Range&& x) noexcept;

  /*!
   * @brief Comparison operator.
   * @param x sensor_msgs::msg::Range_Constants::Range object to compare.
   */
  eProsima_user_DllExport bool operator==(const Range& x) const;

  /*!
   * @brief Comparison operator.
   * @param x sensor_msgs::msg::Range_Constants::Range object to compare.
   */
  eProsima_user_DllExport bool operator!=(const Range& x) const;

  /*!
   * @brief This function copies the value in member header
   * @param _header New value to be copied in member header
   */
  eProsima_user_DllExport void header(
      const std_msgs::msg::Header& _header);

  /*!
   * @brief This function moves the value in member header
   * @param _header New value to be moved in member header
   */
  eProsima_user_DllExport void header(std_msgs::msg::Header&& _header);

  /*!
   * @brief This function returns a constant reference to member header
   * @return Constant reference to member header
   */
  eProsima_user_DllExport const std_msgs::msg::Header& header() const;

  /*!
   * @brief This function returns a reference to member header
   * @return Reference to member header
   */
  eProsima_user_DllExport std_msgs::msg::Header& header();

  /*!
   * @brief This function sets a value in member radiation_type
   * @param _radiation_type New value for member radiation_type
   */
  eProsima_user_DllExport void radiation_type(uint8 _radiation_type);

  /*!
   * @brief This function returns the value of member radiation_type
   * @return Value of member radiation_type
   */
  eProsima_user_DllExport uint8 radiation_type() const;

  /*!
   * @brief This function returns a reference to member radiation_type
   * @return Reference to member radiation_type
   */
  eProsima_user_DllExport uint8& radiation_type();

  /*!
   * @brief This function sets a value in member field_of_view
   * @param _field_of_view New value for member field_of_view
   */
  eProsima_user_DllExport void field_of_view(float _field_of_view);

  /*!
   * @brief This function returns the value of member field_of_view
   * @return Value of member field_of_view
   */
  eProsima_user_DllExport float field_of_view() const;

  /*!
   * @brief This function returns a reference to member field_of_view
   * @return Reference to member field_of_view
   */
  eProsima_user_DllExport float& field_of_view();

  /*!
   * @brief This function sets a value in member min_range
   * @param _min_range New value for member min_range
   */
  eProsima_user_DllExport void min_range(float _min_range);

  /*!
   * @brief This function returns the value of member min_range
   * @return Value of member min_range
   */
  eProsima_user_DllExport float min_range() const;

  /*!
   * @brief This function returns a reference to member min_range
   * @return Reference to member min_range
   */
  eProsima_user_DllExport float& min_range();

  /*!
   * @brief This function sets a value in member max_range
   * @param _max_range New value for member max_range
   */
  eProsima_user_DllExport void max_range(float _max_range);

  /*!
   * @brief This function returns the value of member max_range
   * @return Value of member max_range
   */
  eProsima_user_DllExport float max_range() const;

  /*!
   * @brief This function returns a reference to member max_range
   * @return Reference to member max_range
   */
  eProsima_user_DllExport float& max_range();

  /*!
   * @brief This function sets a value in member range
   * @param _range New value for member range
   */
  eProsima_user_DllExport void range(float _range);

  /*!
   * @brief This function returns the value of member range
   * @return Value of member range
   */
  eProsima_user_DllExport float range() const;

  /*!
   * @brief This function returns a reference to member range
   * @return Reference to member range
   */
  eProsima_user_DllExport float& range();

 private:
  std_msgs::msg::Header m_header;
  uint8 m_radiation_type;
  float m_field_of_view;
  float m_min_range;
  float m_max_range;
  float m_range;

 public:
  typedef Range type;

  eProsima_user_DllExport Range();

  eProsima_user_DllExport ~Range() override;

  eProsima_user_DllExport bool serialize(
      void* data,
      eprosima::fastrtps::rtps::SerializedPayload_t* payload) override {
    return serialize(data, payload,
                     eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport bool serialize(
      void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool deserialize(
      eprosima::fastrtps::rtps::SerializedPayload_t* payload,
      void* data) override;

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data) override {
    return getSerializedSizeProvider(
        data, eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport std::function<uint32_t()> getSerializedSizeProvider(
      void* data,
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      override;

  eProsima_user_DllExport bool getKey(
      void* data, eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
      bool force_md5 = false) override;

  eProsima_user_DllExport void* createData() override;

  eProsima_user_DllExport void deleteData(void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
  eProsima_user_DllExport inline bool is_bounded() const override {
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
  eProsima_user_DllExport inline bool is_plain() const override {
    return is_plain(eprosima::fastdds::dds::DEFAULT_DATA_REPRESENTATION);
  }

  eProsima_user_DllExport inline bool is_plain(
      eprosima::fastdds::dds::DataRepresentationId_t data_representation)
      const override {
    static_cast<void>(data_representation);
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
  eProsima_user_DllExport inline bool construct_sample(
      void* memory) const override {
    new (memory) Range();
    return true;
  }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

  MD5 m_md5;
  unsigned char* m_keyBuffer;

};

}  // namespace Range_Constants
}  // namespace msg
}  // namespace sensor_msgs

#endif  // _FAST_DDS_GENERATED_SENSOR_MSGS_MSG_RANGE_CONSTANTS_RANGE_H_